import type {
  User,
  Transaction,
  Creator,
  Video,
  Category,
  FeaturedCreator,
  Device,
  DashboardStats,
  ChartDataPoint,
  DashboardOverview,
  PayoutRequest,
  KYCUser,
  AdminUser,
  Role,
  Permission,
  FeeConfiguration,
  Playlist,
  Comment,
  UserProfile,
  ActivityLog,
} from "@/types";

export const mockUsers: User[] = [
  {
    id: "1",
    email: "admin@tese.com",
    name: "TESE Admin",
    role: "admin",
    avatar: "",
    createdAt: new Date("2024-01-01"),
    lastLogin: new Date(),
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: "txn_001",
    userId: "user_001",
    userName: "John Doe",
    amount: 29.99,
    currency: "USD",
    type: "payment",
    status: "completed",
    description: "Video subscription - Premium Plan",
    createdAt: new Date("2024-01-15T10:30:00"),
  },
  {
    id: "txn_002",
    userId: "user_002",
    userName: "Jane Smith",
    amount: 14.99,
    currency: "USD",
    type: "payment",
    status: "pending",
    description: "Video purchase - Tutorial Series",
    createdAt: new Date("2024-01-15T11:45:00"),
  },
  {
    id: "txn_003",
    userId: "user_003",
    userName: "Bob Wilson",
    amount: 99.99,
    currency: "USD",
    type: "withdrawal",
    status: "completed",
    description: "Creator payout - January earnings",
    createdAt: new Date("2024-01-14T15:20:00"),
  },
  {
    id: "txn_004",
    userId: "user_001",
    userName: "John Doe",
    amount: 29.99,
    currency: "USD",
    type: "refund",
    status: "refunded",
    description: "Refund - Duplicate purchase",
    createdAt: new Date("2024-01-13T09:15:00"),
  },
  {
    id: "txn_005",
    userId: "user_004",
    userName: "Alice Brown",
    amount: 49.99,
    currency: "USD",
    type: "payment",
    status: "flagged",
    description: "Video subscription - Annual Plan",
    createdAt: new Date("2024-01-15T14:00:00"),
  },
  {
    id: "txn_006",
    userId: "user_005",
    userName: "Charlie Davis",
    amount: 19.99,
    currency: "USD",
    type: "payment",
    status: "failed",
    description: "Video purchase - Masterclass",
    createdAt: new Date("2024-01-15T16:30:00"),
  },
  {
    id: "txn_007",
    userId: "user_006",
    userName: "Diana Evans",
    amount: 250.0,
    currency: "USD",
    type: "deposit",
    status: "completed",
    description: "Wallet deposit",
    createdAt: new Date("2024-01-12T08:00:00"),
  },
  {
    id: "txn_008",
    userId: "user_002",
    userName: "Jane Smith",
    amount: 75.0,
    currency: "USD",
    type: "withdrawal",
    status: "pending",
    description: "Creator payout - Week 2",
    createdAt: new Date("2024-01-15T12:00:00"),
  },
];

export const mockCreators: Creator[] = [
  {
    id: "cr_001",
    firstName: "Tech",
    lastName: "Master",
    creatorFullName: "Tech Master",
    description: "Passionate technology educator bringing complex coding concepts to beginners through clear, step-by-step tutorials and practical projects.",
    phoneNumber: "+27 82 123 4567",
    isCompany: false,
    email: "techmaster@example.com",
    mobileNumber: "+27 82 123 4567",
    avatar: "https://i.pravatar.cc/150?u=techmaster",
    coverImage: "",

    // Payout Information
    payoutType: "bank",
    bankName: "First National Bank",
    bankAccountNumber: "1234567890",

    // Verification Images
    selfie: "https://i.pravatar.cc/300?u=techmaster_selfie",
    idImage: "https://i.pravatar.cc/300?u=techmaster_id",
    idType: "national_id",
    idNumber: "123456789",
    idCopyUrl: "https://i.pravatar.cc/300?u=techmaster_id_copy",
    proofOfResidenceUrl: "https://i.pravatar.cc/400?u=techmaster_por",

    // Channel Information
    channelId: "ch_001",
    channelName: "TechMaster Official",
    channelUrl: "https://tese.com/channel/techmaster",
    channelStatus: "deactivated",
    channelDeactivationComment: "Channel suspended due to non-compliance with platform revenue sharing policies. Creator failed to provide required tax documentation within the specified timeframe.",
    channelTrailer: "https://www.w3schools.com/html/mov_bbb.mp4",

    // Playlist Information
    playlists: [
      {
        id: "pl_001",
        playlistName: "Beginner Tutorials",
        description: "Starting point for new developers",
        thumbnail: "https://i.pravatar.cc/400?u=beginner",
        paymentType: "subscription",
        price: 9.99,
        videoCount: 12,
        totalViews: 45000,
        totalLikes: 2250,
        isActive: true,
        isDeactivated: false,
        creatorId: "cr_001",
        creatorName: "Tech Master",
        channelId: "ch_001",
        channelName: "TechMaster Official",
        videos: [],
        createdAt: new Date("2023-06-01"),
        updatedAt: new Date("2024-01-01"),
      },
      {
        id: "pl_002",
        playlistName: "Advanced Courses",
        description: "Advanced topics for experienced developers",
        thumbnail: "https://i.pravatar.cc/400?u=advanced",
        paymentType: "subscription",
        price: 19.99,
        videoCount: 8,
        totalViews: 32000,
        totalLikes: 1600,
        isActive: true,
        isDeactivated: false,
        creatorId: "cr_001",
        creatorName: "Tech Master",
        channelId: "ch_001",
        channelName: "TechMaster Official",
        videos: [],
        createdAt: new Date("2023-08-15"),
        updatedAt: new Date("2024-01-05"),
      },
    ],

    // Video Information
    videos: [],
    totalVideos: 156,
    totalViews: 2500000,
    totalLikes: 125000,

    // Financial Information
    totalEarnings: 15000,
    totalRevenue: 15000,
    totalPaidOut: 8000,
    currentBalance: 7000,

    // Content Categories
    contentCategories: [
      {
        id: "cc_001",
        channelName: "Technology",
        paymentType: "subscription",
        price: 9.99,
      },
      {
        id: "cc_002",
        channelName: "Education",
        paymentType: "free",
      },
    ],

    status: "active",
    onlineStatus: "online",
    kycStatus: "approved",
    lastSeen: new Date(),
    createdAt: new Date("2023-06-15"),
    updatedAt: new Date("2024-01-01"),
    weeklyEarnings: 0,
    monthlyEarnings: 0,
    yearlyEarnings: 0
  },
  {
    id: "cr_002",
    firstName: "Cooking",
    lastName: "Expert",
    creatorFullName: "Cooking Expert",
    description: "Professional chef sharing delicious recipes, cooking tips, and culinary techniques from around the world. Join me on a flavorful journey!",
    phoneNumber: "+27 83 234 5678",
    isCompany: false,
    email: "cookingexpert@example.com",
    mobileNumber: "+27 83 234 5678",
    avatar: "https://i.pravatar.cc/150?u=cookingexpert",
    coverImage: "",

    // Payout Information
    payoutType: "mobile_wallet",
    bankName: "EcoBank",
    bankAccountNumber: "0987654321",

    // Verification Images
    selfie: "https://i.pravatar.cc/300?u=cookingexpert_selfie",
    idImage: "https://i.pravatar.cc/300?u=cookingexpert_id",
    proofOfResidenceUrl: "https://i.pravatar.cc/400?u=cookingexpert_por",

    // Channel Information
    channelId: "ch_002",
    channelName: "Chef's Kitchen",
    channelUrl: "https://tese.com/channel/cookingexpert",
    channelStatus: "active",

    // Playlist Information
    playlists: [
      {
        id: "pl_003",
        playlistName: "Quick Recipes",
        description: "Fast and easy recipes for busy days",
        thumbnail: "https://i.pravatar.cc/400?u=recipes",
        paymentType: "per_view",
        price: 2.99,
        videoCount: 25,
        totalViews: 156000,
        totalLikes: 7800,
        isActive: true,
        isDeactivated: false,
        creatorId: "cr_002",
        creatorName: "Cooking Expert",
        channelId: "ch_002",
        channelName: "Chef's Kitchen",
        videos: [],
        createdAt: new Date("2023-07-10"),
        updatedAt: new Date("2024-01-08"),
      },
    ],

    // Video Information
    videos: [],
    totalVideos: 89,
    totalViews: 1800000,
    totalLikes: 90000,

    // Financial Information
    totalEarnings: 12000,
    totalRevenue: 12000,
    totalPaidOut: 10000,
    currentBalance: 2000,

    // Content Categories
    contentCategories: [
      {
        id: "cc_003",
        channelName: "Food & Cooking",
        paymentType: "per_view",
        price: 2.99,
      },
    ],

    status: "active",
    onlineStatus: "away",
    kycStatus: "pending_approval",
    lastSeen: new Date(Date.now() - 3600000),
    createdAt: new Date("2023-08-20"),
    updatedAt: new Date("2024-01-02"),
    weeklyEarnings: 0,
    monthlyEarnings: 0,
    yearlyEarnings: 0
  },
  {
    id: "cr_003",
    firstName: "Digital",
    lastName: "Marketing Pro",
    creatorFullName: "Digital Marketing Pro",
    description: "Helping businesses grow through strategic digital marketing. Expert in SEO, social media, content marketing, and online advertising.",
    phoneNumber: "+27 84 345 6789",
    isCompany: true,
    companyName: "DM Pro Agency",
    VAT: "ZA1234567890",
    tinNumber: "TIN123456789",
    email: "digitalmarketing@example.com",
    mobileNumber: "+27 84 345 6789",
    avatar: "https://i.pravatar.cc/150?u=digitalmarketing",
    coverImage: "",

    // Payout Information
    payoutType: "bank",
    bankName: "Standard Bank",
    bankAccountNumber: "1122334455",

    // Verification Images
    selfie: "https://i.pravatar.cc/300?u=digitalmarketing_selfie",
    idImage: "https://i.pravatar.cc/300?u=digitalmarketing_id",
    proofOfResidenceUrl: "https://i.pravatar.cc/400?u=digitalmarketing_por",

    // Channel Information
    channelId: "ch_003",
    channelName: "Digital Marketing Pro",
    channelUrl: "https://tese.com/channel/digitalmarketing",
    channelStatus: "active",

    // Playlist Information
    playlists: [
      {
        id: "pl_004",
        playlistName: "SEO Mastery",
        description: "Complete SEO training program",
        thumbnail: "https://i.pravatar.cc/400?u=seo-mastery",
        paymentType: "subscription",
        price: 29.99,
        videoCount: 15,
        totalViews: 89000,
        totalLikes: 4450,
        isActive: true,
        isDeactivated: false,
        creatorId: "cr_003",
        creatorName: "Digital Marketing Pro",
        channelId: "ch_003",
        channelName: "Digital Marketing Pro",
        videos: [],
        createdAt: new Date("2023-05-20"),
        updatedAt: new Date("2023-12-15"),
      },
    ],

    // Video Information
    videos: [],
    totalVideos: 45,
    totalViews: 950000,
    totalLikes: 47500,

    // Financial Information
    totalEarnings: 25000,
    totalRevenue: 25000,
    totalPaidOut: 18000,
    currentBalance: 7000,

    // Content Categories
    contentCategories: [
      {
        id: "cc_004",
        channelName: "Marketing",
        paymentType: "subscription",
        price: 29.99,
      },
    ],

    status: "active",
    onlineStatus: "offline",
    kycStatus: "declined",
    lastSeen: new Date(Date.now() - 86400000),
    createdAt: new Date("2023-03-10"),
    updatedAt: new Date("2023-12-28"),
    weeklyEarnings: 0,
    monthlyEarnings: 0,
    yearlyEarnings: 0
  },
  {
    id: "cr_004",
    firstName: "Fitness",
    lastName: "Coach",
    creatorFullName: "Fitness Coach",
    description: "Certified personal trainer helping you achieve your fitness goals. Customized workout plans, nutrition guidance, and motivation.",
    phoneNumber: "+27 85 456 7890",
    isCompany: false,
    email: "fitnesscoach@example.com",
    mobileNumber: "+27 85 456 7890",
    avatar: "https://i.pravatar.cc/150?u=fitnesscoach",
    coverImage: "",

    // Payout Information
    payoutType: "mobile_wallet",
    bankName: "Absa Bank",
    bankAccountNumber: "5566778899",

    // Verification Images
    selfie: "https://i.pravatar.cc/300?u=fitnesscoach_selfie",
    idImage: "https://i.pravatar.cc/300?u=fitnesscoach_id",

    // Channel Information
    channelId: "ch_004",
    channelName: "FitLife Training",
    channelUrl: "https://tese.com/channel/fitnesscoach",
    channelStatus: "deactivated",
    channelDeactivationComment: "Channel suspended due to multiple community guideline violations. Content was found to be in violation of T&Cs regarding inappropriate fitness advice and misleading health claims.",
    channelTrailer: "https://www.w3schools.com/html/movie.mp4",

    // Playlist Information
    playlists: [],

    // Video Information
    videos: [],
    totalVideos: 120,
    totalViews: 3200000,
    totalLikes: 160000,

    // Financial Information
    totalEarnings: 18000,
    totalRevenue: 18000,
    totalPaidOut: 15000,
    currentBalance: 3000,

    // Content Categories
    contentCategories: [
      {
        id: "cc_005",
        channelName: "Fitness",
        paymentType: "subscription",
        price: 14.99,
      },
    ],

    status: "suspended",
    onlineStatus: "offline",
    kycStatus: "pending",
    lastSeen: new Date(Date.now() - 172800000),
    createdAt: new Date("2023-01-05"),
    updatedAt: new Date("2024-01-03"),
    weeklyEarnings: 0,
    monthlyEarnings: 0,
    yearlyEarnings: 0
  },
];

export const mockVideos: Video[] = [
  {
    id: "vid_001",
    title: "Big Buck Bunny - Sample Video",
    description: "A sample video for testing",
    videoName: "Big Buck Bunny",
    videoDescription: "Big Buck Bunny sample video",
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    thumbnail:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/BigBuckBunny.jpg",
    videoTrailer: "https://www.w3schools.com/html/mov_bbb.mp4",
    duration: 596,
    creatorId: "cr_001",
    creatorName: "Tech Master",
    categoryId: "cat_001",
    categoryName: "Technology",
    status: "published",
    isFeatured: true,
    isBanner: false,
    isPaid: false,
    comments: 150,
    videoComments: 150,
    commentsHidden: false,
    views: 45000,
    likes: 2250,
    shares: 75,
    watchTime: 360000,
    engagementRate: 5.5,
    paymentType: "free",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
    viewsByPeriod: {
      daily: [
        { date: "2024-01-04", views: 1200 },
        { date: "2024-01-05", views: 1500 },
        { date: "2024-01-06", views: 1800 },
        { date: "2024-01-07", views: 2200 },
        { date: "2024-01-08", views: 2800 },
        { date: "2024-01-09", views: 3500 },
        { date: "2024-01-10", views: 4200 },
      ],
      weekly: [
        { week: "Week 1", views: 8500 },
        { week: "Week 2", views: 12000 },
        { week: "Week 3", views: 14500 },
        { week: "Week 4", views: 10000 },
      ],
      monthly: [
        { month: "Jan 2023", views: 0 },
        { month: "Feb 2023", views: 0 },
        { month: "Mar 2023", views: 0 },
        { month: "Apr 2023", views: 0 },
        { month: "May 2023", views: 0 },
        { month: "Jun 2023", views: 0 },
        { month: "Jul 2023", views: 0 },
        { month: "Aug 2023", views: 0 },
        { month: "Sep 2023", views: 0 },
        { month: "Oct 2023", views: 0 },
        { month: "Nov 2023", views: 5000 },
        { month: "Dec 2023", views: 15000 },
        { month: "Jan 2024", views: 45000 },
      ],
      yearly: [
        { year: "2021", views: 0 },
        { year: "2022", views: 5000 },
        { year: "2023", views: 35000 },
        { year: "2024", views: 45000 },
      ],
    },
  },
  {
    id: "vid_002",
    title: "Elephant Dream - YouTube Video",
    description: "A famous open movie from Blender Foundation",
    videoName: "Elephant Dream",
    videoDescription: "Elephant Dream open movie",
    videoUrl: "https://www.youtube.com/watch?v=18-x-2Sva4Q",
    thumbnail:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ElephantsDream.jpg",
    videoTrailer: "https://www.w3schools.com/html/movie.mp4",
    duration: 653,
    creatorId: "cr_001",
    creatorName: "Tech Master",
    categoryId: "cat_001",
    categoryName: "Technology",
    status: "published",
    isFeatured: false,
    isBanner: true,
    isPaid: true,
    currency: "USD",
    price: 9.99,
    comments: 89,
    videoComments: 89,
    commentsHidden: false,
    views: 28000,
    likes: 1400,
    shares: 45,
    watchTime: 192000,
    engagementRate: 5.3,
    paymentType: "per_view",
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-08"),
    viewsByPeriod: {
      daily: [
        { date: "2024-01-04", views: 800 },
        { date: "2024-01-05", views: 1000 },
        { date: "2024-01-06", views: 1200 },
        { date: "2024-01-07", views: 1500 },
        { date: "2024-01-08", views: 2000 },
        { date: "2024-01-09", views: 2500 },
        { date: "2024-01-10", views: 3000 },
      ],
      weekly: [
        { week: "Week 1", views: 5000 },
        { week: "Week 2", views: 7500 },
        { week: "Week 3", views: 8500 },
        { week: "Week 4", views: 7000 },
      ],
      monthly: [
        { month: "Jan 2023", views: 0 },
        { month: "Feb 2023", views: 0 },
        { month: "Mar 2023", views: 0 },
        { month: "Apr 2023", views: 0 },
        { month: "May 2023", views: 0 },
        { month: "Jun 2023", views: 0 },
        { month: "Jul 2023", views: 0 },
        { month: "Aug 2023", views: 0 },
        { month: "Sep 2023", views: 0 },
        { month: "Oct 2023", views: 0 },
        { month: "Nov 2023", views: 3000 },
        { month: "Dec 2023", views: 10000 },
        { month: "Jan 2024", views: 28000 },
      ],
      yearly: [
        { year: "2021", views: 0 },
        { year: "2022", views: 2000 },
        { year: "2023", views: 20000 },
        { year: "2024", views: 28000 },
      ],
    },
  },
  {
    id: "vid_003",
    title: "Sintel - Sample Video",
    description: "Another amazing open movie",
    videoName: "Sintel",
    videoDescription: "Sintel open movie",
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    thumbnail:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/Sintel.jpg",
    duration: 888,
    creatorId: "cr_002",
    creatorName: "Cooking Expert",
    categoryId: "cat_002",
    categoryName: "Food & Cooking",
    status: "published",
    isFeatured: false,
    isBanner: false,
    isPaid: true,
    currency: "USD",
    price: 2.99,
    comments: 450,
    videoComments: 450,
    commentsHidden: false,
    views: 120000,
    likes: 6000,
    shares: 300,
    watchTime: 540000,
    engagementRate: 5.8,
    paymentType: "per_view",
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    id: "vid_004",
    title: "Tears of Steel - Sample Video",
    description: "Sci-fi short film",
    videoName: "Tears of Steel",
    videoDescription: "Tears of Steel sci-fi short",
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    thumbnail:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/TearsOfSteel.jpg",
    duration: 734,
    creatorId: "cr_004",
    creatorName: "Fitness Coach",
    categoryId: "cat_003",
    categoryName: "Fitness",
    status: "published",
    isFeatured: true,
    isBanner: true,
    isPaid: false,
    comments: 890,
    videoComments: 890,
    commentsHidden: false,
    views: 250000,
    likes: 12500,
    shares: 560,
    watchTime: 900000,
    engagementRate: 5.6,
    paymentType: "free",
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05"),
  },
  {
    id: "vid_005",
    title: "For Bigger Blazes - Sample Video",
    description: "Google Chrome promotional video",
    videoName: "For Bigger Blazes",
    videoDescription: "For Bigger Blazes sample",
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    thumbnail:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerBlazes.jpg",
    duration: 15,
    creatorId: "cr_003",
    creatorName: "Digital Marketing Pro",
    categoryId: "cat_004",
    categoryName: "Marketing",
    status: "published",
    isFeatured: false,
    isBanner: false,
    isPaid: true,
    currency: "USD",
    price: 19.99,
    comments: 120,
    videoComments: 120,
    commentsHidden: false,
    views: 35000,
    likes: 1750,
    shares: 85,
    watchTime: 252000,
    engagementRate: 5.4,
    paymentType: "subscription",
    createdAt: new Date("2024-01-14"),
    updatedAt: new Date("2024-01-14"),
  },
  {
    id: "vid_006",
    title: "YouTube Video Sample",
    description: "A YouTube embedded video for testing",
    videoName: "YouTube Sample",
    videoDescription: "YouTube video sample",
    videoUrl: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
    thumbnail: "https://i.ytimg.com/vi/LXb3EKWsInQ/maxresdefault.jpg",
    duration: 183,
    creatorId: "cr_001",
    creatorName: "Tech Master",
    categoryId: "cat_001",
    categoryName: "Technology",
    status: "published",
    isFeatured: true,
    isBanner: false,
    isPaid: false,
    comments: 234,
    videoComments: 234,
    commentsHidden: false,
    views: 89000,
    likes: 4450,
    shares: 120,
    watchTime: 450000,
    engagementRate: 5.2,
    paymentType: "free",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
];

export const mockPlaylists: Playlist[] = [
  {
    id: "pl_001",
    playlistName: "React Mastery Course",
    description: "Complete React course from basics to advanced",
    thumbnail: "https://i.pravatar.cc/400?u=react-playlist",
    paymentType: "subscription",
    price: 49.99,
    videoCount: 25,
    totalViews: 125000,
    totalLikes: 6250,
    isActive: true,
    isDeactivated: false,
    creatorId: "cr_001",
    creatorName: "Tech Master",
    channelId: "ch_001",
    channelName: "TechMaster Official",
    videos: [mockVideos[0], mockVideos[1]],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "pl_002",
    playlistName: "Italian Cooking Class",
    description: "Learn authentic Italian recipes",
    thumbnail: "https://i.pravatar.cc/400?u=italian-playlist",
    paymentType: "per_view",
    price: 2.99,
    videoCount: 12,
    totalViews: 89000,
    totalLikes: 4450,
    isActive: true,
    isDeactivated: false,
    creatorId: "cr_002",
    creatorName: "Cooking Expert",
    channelId: "ch_002",
    channelName: "Chef's Kitchen",
    videos: [mockVideos[2]],
    createdAt: new Date("2023-12-15"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "pl_003",
    playlistName: "Digital Marketing Basics",
    description: "Introduction to digital marketing strategies",
    thumbnail: "https://i.pravatar.cc/400?u=dm-playlist",
    paymentType: "subscription",
    price: 29.99,
    videoCount: 20,
    totalViews: 67000,
    totalLikes: 3350,
    isActive: true,
    isDeactivated: false,
    creatorId: "cr_003",
    creatorName: "Digital Marketing Pro",
    channelId: "ch_003",
    channelName: "Digital Marketing Pro",
    videos: [mockVideos[4]],
    createdAt: new Date("2023-11-20"),
    updatedAt: new Date("2024-01-05"),
  },
  {
    id: "pl_004",
    playlistName: "Fitness Fundamentals",
    description: "Essential fitness for beginners",
    thumbnail: "https://i.pravatar.cc/400?u=fitness-playlist",
    paymentType: "free",
    videoCount: 15,
    totalViews: 234000,
    totalLikes: 11700,
    isActive: true,
    isDeactivated: false,
    creatorId: "cr_004",
    creatorName: "Fitness Coach",
    channelId: "ch_004",
    channelName: "FitLife Training",
    videos: [mockVideos[3]],
    createdAt: new Date("2023-10-10"),
    updatedAt: new Date("2024-01-02"),
  },
  {
    id: "pl_005",
    playlistName: "TypeScript Deep Dive",
    description: "Advanced TypeScript concepts and patterns",
    thumbnail: "https://i.pravatar.cc/400?u=typescript-playlist",
    paymentType: "per_view",
    price: 5.99,
    videoCount: 8,
    totalViews: 45000,
    totalLikes: 2250,
    isActive: true,
    isDeactivated: false,
    creatorId: "cr_001",
    creatorName: "Tech Master",
    channelId: "ch_001",
    channelName: "TechMaster Official",
    videos: [mockVideos[1]],
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    id: "pl_006",
    playlistName: "SEO Mastery",
    description: "Complete SEO training program",
    thumbnail: "https://i.pravatar.cc/400?u=seo-playlist",
    paymentType: "subscription",
    price: 39.99,
    videoCount: 18,
    totalViews: 78000,
    totalLikes: 3900,
    isActive: true,
    isDeactivated: false,
    creatorId: "cr_003",
    creatorName: "Digital Marketing Pro",
    channelId: "ch_003",
    channelName: "Digital Marketing Pro",
    videos: [mockVideos[4]],
    createdAt: new Date("2023-09-15"),
    updatedAt: new Date("2023-12-20"),
  },
];

export const mockCategories: Category[] = [
  {
    id: "cat_001",
    name: "Comedy",
    slug: "comedy",
    description: "Comedy sketches, stand-up, and humorous content",
    icon: "😄",
    color: "#F59E0B",
    bannerUrl: "/COMEDY.png",
    imageHeight: 80,
    imageWidth: 80,
    imagePosition: "center 80%",
    videoCount: 0,
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "cat_002",
    name: "Drama",
    slug: "drama",
    description: "Dramatic series, movies, and theatrical content",
    icon: "🎭",
    color: "#8B5CF6",
    bannerUrl: "/DRAMA.png",
    imageHeight: 80,
    imageWidth: 80,
    videoCount: 0,
    isActive: true,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "cat_003",
    name: "Fitness",
    slug: "fitness",
    description: "Workouts, health tips, and wellness content",
    icon: "💪",
    color: "#EF4444",
    bannerUrl: "/FITNESS.png",
    imageHeight: 80,
    imageWidth: 80,
    videoCount: 0,
    isActive: true,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "cat_004",
    name: "Music",
    slug: "music",
    description: "Music performances, tutorials, and reviews",
    icon: "🎵",
    color: "#3B82F6",
    bannerUrl: "/MUSIC.png",
    imageHeight: 80,
    imageWidth: 80,
    videoCount: 0,
    isActive: true,
    createdAt: new Date("2024-03-01"),
  },
  {
    id: "cat_005",
    name: "News",
    slug: "news",
    description: "News updates, current events, and analysis",
    icon: "📰",
    color: "#10B981",
    bannerUrl: "/NEWS.png",
    imageHeight: 80,
    imageWidth: 80,
    videoCount: 0,
    isActive: true,
    createdAt: new Date("2024-04-01"),
  },
  {
    id: "cat_006",
    name: "Podcast",
    slug: "podcast",
    description: "Podcast episodes and audio content",
    icon: "🎙️",
    color: "#EC4899",
    bannerUrl: "/PODCAST.png",
    imageHeight: 80,
    imageWidth: 80,
    videoCount: 0,
    isActive: true,
    createdAt: new Date("2024-05-01"),
  },
  {
    id: "cat_007",
    name: "Skits",
    slug: "skits",
    description: "Short comedy sketches and skits",
    icon: "😂",
    color: "#F97316",
    bannerUrl: "/SKITS.png",
    imageHeight: 80,
    imageWidth: 80,
    videoCount: 0,
    isActive: true,
    createdAt: new Date("2024-06-01"),
  },
  {
    id: "cat_008",
    name: "Sports",
    slug: "sports",
    description: "Sports events, highlights, and analysis",
    icon: "⚽",
    color: "#06B6D4",
    bannerUrl: "/SPORTS.png",
    imageHeight: 80,
    imageWidth: 80,
    videoCount: 0,
    isActive: true,
    createdAt: new Date("2024-07-01"),
  },
];

export const mockFeaturedCreators: FeaturedCreator[] = [
  {
    id: "fc_001",
    creatorId: "cr_001",
    creator: mockCreators[0],
    position: 1,
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "fc_002",
    creatorId: "cr_002",
    creator: mockCreators[1],
    position: 2,
    isActive: true,
    createdAt: new Date("2024-01-02"),
  },
  {
    id: "fc_003",
    creatorId: "cr_003",
    creator: mockCreators[2],
    position: 3,
    isActive: true,
    createdAt: new Date("2024-01-03"),
  },
];

export const mockDevices: Device[] = [
  {
    id: "dev_001",
    userId: "user_001",
    deviceType: "desktop",
    browser: "Chrome",
    os: "Windows 11",
    ipAddress: "192.168.1.100",
    location: {
      country: "South Africa",
      city: "Johannesburg",
      timezone: "Africa/Johannesburg",
    },
    lastActive: new Date(),
    isCurrentSession: true,
    isBlocked: false,
  },
  {
    id: "dev_002",
    userId: "user_001",
    deviceType: "mobile",
    browser: "Safari",
    os: "iOS 17",
    ipAddress: "192.168.1.101",
    location: {
      country: "South Africa",
      city: "Johannesburg",
      timezone: "Africa/Johannesburg",
    },
    lastActive: new Date(Date.now() - 3600000),
    isCurrentSession: false,
    isBlocked: false,
  },
];

export const mockDashboardStats: DashboardStats = {
  totalTransactions: 1247,
  totalRevenue: 89450.0,
  totalCreators: 156,
  totalChannels: 142,
  totalVideos: 3420,
  totalViews: 45678900,
  dailyVisitors: 12450,
  dailyViews: 456700,
  activeChannels: 128,
  transactionGrowth: 12.5,
  revenueGrowth: 8.3,
  creatorGrowth: 15.2,
  videoGrowth: 22.1,
};

export const mockTransactionChartData: ChartDataPoint[] = [
  { date: "2024-01-09", value: 4500 },
  { date: "2024-01-10", value: 5200 },
  { date: "2024-01-11", value: 4800 },
  { date: "2024-01-12", value: 6100 },
  { date: "2024-01-13", value: 5500 },
  { date: "2024-01-14", value: 6700 },
  { date: "2024-01-15", value: 7200 },
];

export const mockRevenueChartData: ChartDataPoint[] = [
  { date: "2024-01-09", value: 12500 },
  { date: "2024-01-10", value: 14800 },
  { date: "2024-01-11", value: 13200 },
  { date: "2024-01-12", value: 16500 },
  { date: "2024-01-13", value: 14200 },
  { date: "2024-01-14", value: 17800 },
  { date: "2024-01-15", value: 19200 },
];

export const mockOverviewData: DashboardOverview = {
  transactions: [
    { label: "Payments", value: 845 },
    { label: "Refunds", value: 67 },
    { label: "Withdrawals", value: 289 },
    { label: "Deposits", value: 46 },
  ],
  creators: [
    { label: "Active", value: 128 },
    { label: "Pending", value: 18 },
    { label: "Suspended", value: 10 },
  ],
  traffic: [
    { label: "Direct", value: 45 },
    { label: "Social", value: 32 },
    { label: "Search", value: 18 },
    { label: "Referral", value: 5 },
  ],
  totals: {
    revenue: 89450,
    creators: 156,
    videos: 3420,
    channels: 142,
    views: 45678900,
    visitors: 12450,
  },
};

export const mockPayoutRequests: PayoutRequest[] = [
  {
    id: "pr_001",
    creatorId: "cr_001",
    creatorName: "Tech Master",
    creatorEmail: "techmaster@example.com",
    channelName: "TechMaster Official",
    amount: 500,
    currency: "USD",
    status: "pending",
    bankName: "First National Bank",
    bankAccountNumber: "1234567890",
    accountHolderName: "Tech Master",
    notes: "Monthly payout",
    requestedAt: new Date("2024-01-14"),
  },
  {
    id: "pr_002",
    creatorId: "cr_002",
    creatorName: "Cooking Expert",
    creatorEmail: "cookingexpert@example.com",
    channelName: "Chef's Kitchen",
    amount: 350,
    currency: "USD",
    status: "approved",
    bankName: "EcoBank",
    bankAccountNumber: "0987654321",
    accountHolderName: "Cooking Expert",
    requestedAt: new Date("2024-01-13"),
    processedAt: new Date("2024-01-14"),
    processedBy: "Admin",
  },
];

export const mockKYCUsers: KYCUser[] = [
  {
    id: "kyc_001",
    userId: "user_001",
    firstName: "John",
    lastName: "Doe",
    email: "johndoe@example.com",
    selfieUrl: "https://i.pravatar.cc/300?u=johndoe_selfie",
    idImageUrl: "https://i.pravatar.cc/300?u=johndoe_id",
    idType: "national_id",
    idNumber: "1234567890123",
    status: "pending_approval",
    submittedAt: new Date("2024-01-12"),
  },
  {
    id: "kyc_002",
    userId: "user_002",
    firstName: "Jane",
    lastName: "Smith",
    email: "janesmith@example.com",
    selfieUrl: "https://i.pravatar.cc/300?u=janesmith_selfie",
    idImageUrl: "https://i.pravatar.cc/300?u=janesmith_id",
    idType: "passport",
    idNumber: "AB1234567",
    status: "approved",
    submittedAt: new Date("2024-01-10"),
    reviewedAt: new Date("2024-01-11"),
    reviewedBy: "Admin",
  },
  {
    id: "kyc_003",
    userId: "user_003",
    firstName: "Bob",
    lastName: "Johnson",
    email: "bobjohnson@example.com",
    selfieUrl: "https://i.pravatar.cc/300?u=bobjohnson_selfie",
    idImageUrl: "https://i.pravatar.cc/300?u=bobjohnson_id",
    idType: "drivers_license",
    idNumber: "DL123456789",
    status: "pending",
    submittedAt: new Date("2024-01-14"),
  },
];

export const mockAdminUsers: AdminUser[] = [
  {
    id: "admin_001",
    email: "admin@tese.com",
    name: "TESE Admin",
    role: "super_admin",
    avatar: "",
    isActive: true,
    lastLogin: new Date(),
    createdAt: new Date("2023-01-01"),
  },
  {
    id: "admin_002",
    email: "moderator@tese.com",
    name: "Content Moderator",
    role: "admin",
    avatar: "",
    isActive: true,
    lastLogin: new Date(Date.now() - 86400000),
    createdAt: new Date("2023-06-15"),
  },
];

export const mockPermissions: Permission[] = [
  {
    id: "perm_001",
    name: "View Dashboard",
    description: "Access to dashboard statistics",
    module: "users",
  },
  {
    id: "perm_002",
    name: "Manage Users",
    description: "Create, edit, and delete users",
    module: "users",
  },
  {
    id: "perm_003",
    name: "View Creators",
    description: "Access to creator list",
    module: "creators",
  },
  {
    id: "perm_004",
    name: "Manage Creators",
    description: "Edit creator information and status",
    module: "creators",
  },
  {
    id: "perm_005",
    name: "Approve KYC",
    description: "Approve or reject KYC applications",
    module: "kyc",
  },
  {
    id: "perm_006",
    name: "View Transactions",
    description: "Access to transaction history",
    module: "transactions",
  },
  {
    id: "perm_007",
    name: "Process Payouts",
    description: "Approve and process creator payouts",
    module: "payouts",
  },
  {
    id: "perm_008",
    name: "Manage Settings",
    description: "Access to system settings",
    module: "settings",
  },
];

export const mockRoles: Role[] = [
  {
    id: "role_001",
    name: "Super Admin",
    description: "Full system access",
    permissions: mockPermissions,
    createdAt: new Date("2023-01-01"),
  },
  {
    id: "role_002",
    name: "Admin",
    description: "Administrative access",
    permissions: mockPermissions.slice(2),
    createdAt: new Date("2023-01-15"),
  },
  {
    id: "role_003",
    name: "Editor",
    description: "Content management access",
    permissions: [mockPermissions[2], mockPermissions[5]],
    createdAt: new Date("2023-02-01"),
  },
  {
    id: "role_004",
    name: "Auditor",
    description: "Read-only access",
    permissions: [mockPermissions[0], mockPermissions[2], mockPermissions[5]],
    createdAt: new Date("2023-03-01"),
  },
];

export const mockFeeConfigurations: FeeConfiguration[] = [
  {
    id: "fee_001",
    type: "platform",
    name: "Platform Fee",
    percentage: 10,
    fixedAmount: 0,
    isActive: true,
    createdAt: new Date("2023-01-01"),
    updatedAt: new Date("2023-01-01"),
  },
  {
    id: "fee_002",
    type: "service",
    name: "Transaction Fee",
    percentage: 2.9,
    fixedAmount: 0.3,
    isActive: true,
    createdAt: new Date("2023-01-01"),
    updatedAt: new Date("2023-01-01"),
  },
  {
    id: "fee_003",
    type: "payout",
    name: "Payout Fee",
    percentage: 1,
    fixedAmount: 0.25,
    isActive: true,
    createdAt: new Date("2023-01-01"),
    updatedAt: new Date("2023-01-01"),
  },
  {
    id: "fee_004",
    type: "subscription",
    name: "Subscription Fee",
    percentage: 5,
    fixedAmount: 0,
    isActive: true,
    createdAt: new Date("2023-01-01"),
    updatedAt: new Date("2023-01-01"),
  },
];

export const mockComments: Comment[] = [
  {
    id: "cmt_001",
    userId: "user_001",
    userName: "John Doe",
    userEmail: "john.doe@example.com",
    userAvatar: "https://i.pravatar.cc/150?u=john",
    videoId: "vid_001",
    videoTitle: "Big Buck Bunny - Sample Video",
    content: "This is an amazing video! The animation quality is incredible.",
    status: "active",
    isFlagged: false,
    isHidden: false,
    flags: 0,
    likes: 45,
    replies: 3,
    likedBy: [
      {
        id: "like_001",
        name: "Alice Brown",
        avatar: "https://i.pravatar.cc/150?u=alice",
      },
      {
        id: "like_002",
        name: "Charlie Davis",
        avatar: "https://i.pravatar.cc/150?u=charlie",
      },
      {
        id: "like_003",
        name: "Diana Evans",
        avatar: "https://i.pravatar.cc/150?u=diana",
      },
      {
        id: "like_004",
        name: "Edward Foster",
        avatar: "https://i.pravatar.cc/150?u=edward",
      },
      {
        id: "like_005",
        name: "Fiona Green",
        avatar: "https://i.pravatar.cc/150?u=fiona",
      },
    ],
    repliedBy: [
      {
        id: "rep_001",
        name: "Jane Smith",
        avatar: "https://i.pravatar.cc/150?u=jane",
        content: "I agree! The animation is top notch.",
        createdAt: new Date("2024-01-10T15:00:00"),
      },
      {
        id: "rep_002",
        name: "Bob Wilson",
        avatar: "https://i.pravatar.cc/150?u=bob",
        content: "Agreed! Best animation I've seen.",
        createdAt: new Date("2024-01-10T16:00:00"),
      },
      {
        id: "rep_003",
        name: "George Harris",
        avatar: "https://i.pravatar.cc/150?u=george",
        content: "The attention to detail is amazing!",
        createdAt: new Date("2024-01-10T17:00:00"),
      },
    ],
    createdAt: new Date("2024-01-10T14:30:00"),
    updatedAt: new Date("2024-01-10T14:30:00"),
  },
  {
    id: "cmt_002",
    userId: "user_002",
    userName: "Jane Smith",
    userEmail: "jane.smith@example.com",
    userAvatar: "https://i.pravatar.cc/150?u=jane",
    videoId: "vid_001",
    videoTitle: "Big Buck Bunny - Sample Video",
    content: "Great content! Would love to see more videos like this.",
    status: "active",
    isFlagged: false,
    isHidden: false,
    flags: 0,
    likes: 32,
    replies: 1,
    likedBy: [
      {
        id: "like_006",
        name: "John Doe",
        avatar: "https://i.pravatar.cc/150?u=john",
      },
      {
        id: "like_007",
        name: "Alice Brown",
        avatar: "https://i.pravatar.cc/150?u=alice",
      },
      {
        id: "like_008",
        name: "Ian Thompson",
        avatar: "https://i.pravatar.cc/150?u=ian",
      },
    ],
    repliedBy: [
      {
        id: "rep_004",
        name: "Hannah White",
        avatar: "https://i.pravatar.cc/150?u=hannah",
        content: "More content please!",
        createdAt: new Date("2024-01-10T16:00:00"),
      },
    ],
    createdAt: new Date("2024-01-10T15:45:00"),
    updatedAt: new Date("2024-01-10T15:45:00"),
  },
  {
    id: "cmt_003",
    userId: "user_003",
    userName: "Bob Wilson",
    userEmail: "bob.wilson@example.com",
    userAvatar: "https://i.pravatar.cc/150?u=bob",
    videoId: "vid_002",
    videoTitle: "Elephant Dream - YouTube Video",
    content:
      "I think this video contains inappropriate content. Should be reviewed.",
    status: "flagged",
    isFlagged: true,
    isHidden: false,
    flags: 5,
    likes: 2,
    replies: 0,
    likedBy: [
      {
        id: "like_009",
        name: "Julia Adams",
        avatar: "https://i.pravatar.cc/150?u=julia",
      },
      {
        id: "like_010",
        name: "Fiona Green",
        avatar: "https://i.pravatar.cc/150?u=fiona",
      },
    ],
    repliedBy: [],
    createdAt: new Date("2024-01-11T09:15:00"),
    updatedAt: new Date("2024-01-12T10:00:00"),
  },
  {
    id: "cmt_004",
    userId: "user_004",
    userName: "Alice Brown",
    userEmail: "alice.brown@example.com",
    userAvatar: "https://i.pravatar.cc/150?u=alice",
    videoId: "vid_002",
    videoTitle: "Elephant Dream - YouTube Video",
    content: "Beautiful animation! The colors are so vibrant.",
    status: "active",
    isFlagged: false,
    isHidden: false,
    flags: 0,
    likes: 28,
    replies: 2,
    likedBy: [
      {
        id: "like_011",
        name: "Jane Smith",
        avatar: "https://i.pravatar.cc/150?u=jane",
      },
      {
        id: "like_012",
        name: "Charlie Davis",
        avatar: "https://i.pravatar.cc/150?u=charlie",
      },
      {
        id: "like_013",
        name: "Edward Foster",
        avatar: "https://i.pravatar.cc/150?u=edward",
      },
    ],
    repliedBy: [
      {
        id: "rep_005",
        name: "John Doe",
        avatar: "https://i.pravatar.cc/150?u=john",
        content: "The color grading is exceptional!",
        createdAt: new Date("2024-01-11T11:00:00"),
      },
      {
        id: "rep_006",
        name: "Diana Evans",
        avatar: "https://i.pravatar.cc/150?u=diana",
        content: "Absolutely stunning visuals!",
        createdAt: new Date("2024-01-11T12:00:00"),
      },
    ],
    createdAt: new Date("2024-01-11T10:30:00"),
    updatedAt: new Date("2024-01-11T10:30:00"),
  },
  {
    id: "cmt_005",
    userId: "user_005",
    userName: "Charlie Davis",
    userEmail: "charlie.davis@example.com",
    userAvatar: "https://i.pravatar.cc/150?u=charlie",
    videoId: "vid_003",
    videoTitle: "Sintel - Sample Video",
    content:
      "This comment contains spam content and should be hidden. Visit my channel for free gifts! $ SPAM $ ",
    status: "hidden",
    isFlagged: true,
    isHidden: true,
    flags: 12,
    likes: 0,
    replies: 0,
    likedBy: [],
    repliedBy: [],
    createdAt: new Date("2024-01-11T11:00:00"),
    updatedAt: new Date("2024-01-11T16:00:00"),
  },
  {
    id: "cmt_006",
    userId: "user_006",
    userName: "Diana Evans",
    userEmail: "diana.evans@example.com",
    userAvatar: "https://i.pravatar.cc/150?u=diana",
    videoId: "vid_003",
    videoTitle: "Sintel - Sample Video",
    content: "The story is so touching! I cried at the end.",
    status: "active",
    isFlagged: false,
    isHidden: false,
    flags: 0,
    likes: 56,
    replies: 5,
    likedBy: [
      {
        id: "like_014",
        name: "Alice Brown",
        avatar: "https://i.pravatar.cc/150?u=alice",
      },
      {
        id: "like_015",
        name: "Bob Wilson",
        avatar: "https://i.pravatar.cc/150?u=bob",
      },
      {
        id: "like_016",
        name: "Jane Smith",
        avatar: "https://i.pravatar.cc/150?u=jane",
      },
      {
        id: "like_017",
        name: "George Harris",
        avatar: "https://i.pravatar.cc/150?u=george",
      },
      {
        id: "like_018",
        name: "Hannah White",
        avatar: "https://i.pravatar.cc/150?u=hannah",
      },
      {
        id: "like_019",
        name: "Ian Thompson",
        avatar: "https://i.pravatar.cc/150?u=ian",
      },
    ],
    repliedBy: [
      {
        id: "rep_007",
        name: "Fiona Green",
        avatar: "https://i.pravatar.cc/150?u=fiona",
        content: "Me too! The emotional depth is incredible.",
        createdAt: new Date("2024-01-11T13:00:00"),
      },
      {
        id: "rep_008",
        name: "Edward Foster",
        avatar: "https://i.pravatar.cc/150?u=edward",
        content: "The ending really got to me.",
        createdAt: new Date("2024-01-11T14:00:00"),
      },
      {
        id: "rep_009",
        name: "Julia Adams",
        avatar: "https://i.pravatar.cc/150?u=julia",
        content: "Such a beautiful story!",
        createdAt: new Date("2024-01-11T15:00:00"),
      },
    ],
    createdAt: new Date("2024-01-11T12:15:00"),
    updatedAt: new Date("2024-01-11T12:15:00"),
  },
  {
    id: "cmt_007",
    userId: "user_007",
    userName: "Edward Foster",
    userEmail: "edward.foster@example.com",
    userAvatar: "https://i.pravatar.cc/150?u=edward",
    videoId: "vid_004",
    videoTitle: "Tears of Steel - Sample Video",
    content: "This is inappropriate content. Flagging this comment.",
    status: "flagged",
    isFlagged: true,
    isHidden: false,
    flags: 3,
    likes: 1,
    replies: 0,
    likedBy: [
      {
        id: "like_020",
        name: "Charlie Davis",
        avatar: "https://i.pravatar.cc/150?u=charlie",
      },
    ],
    repliedBy: [],
    createdAt: new Date("2024-01-12T08:45:00"),
    updatedAt: new Date("2024-01-12T14:00:00"),
  },
  {
    id: "cmt_008",
    userId: "user_008",
    userName: "Fiona Green",
    userEmail: "fiona.green@example.com",
    userAvatar: "https://i.pravatar.cc/150?u=fiona",
    videoId: "vid_004",
    videoTitle: "Tears of Steel - Sample Video",
    content: "Love the visual effects! Great work by the team.",
    status: "active",
    isFlagged: false,
    isHidden: false,
    flags: 0,
    likes: 38,
    replies: 4,
    likedBy: [
      {
        id: "like_021",
        name: "Diana Evans",
        avatar: "https://i.pravatar.cc/150?u=diana",
      },
      {
        id: "like_022",
        name: "John Doe",
        avatar: "https://i.pravatar.cc/150?u=john",
      },
      {
        id: "like_023",
        name: "Alice Brown",
        avatar: "https://i.pravatar.cc/150?u=alice",
      },
      {
        id: "like_024",
        name: "Ian Thompson",
        avatar: "https://i.pravatar.cc/150?u=ian",
      },
    ],
    repliedBy: [
      {
        id: "rep_010",
        name: "Jane Smith",
        avatar: "https://i.pravatar.cc/150?u=jane",
        content: "The VFX team did an amazing job!",
        createdAt: new Date("2024-01-12T10:00:00"),
      },
      {
        id: "rep_011",
        name: "Bob Wilson",
        avatar: "https://i.pravatar.cc/150?u=bob",
        content: "Really impressive work!",
        createdAt: new Date("2024-01-12T11:00:00"),
      },
    ],
    createdAt: new Date("2024-01-12T09:30:00"),
    updatedAt: new Date("2024-01-12T09:30:00"),
  },
  {
    id: "cmt_009",
    userId: "user_009",
    userName: "George Harris",
    userEmail: "george.harris@example.com",
    userAvatar: "https://i.pravatar.cc/150?u=george",
    videoId: "vid_001",
    videoTitle: "Big Buck Bunny - Sample Video",
    content: "Could you make more tutorials like this? Very educational.",
    status: "active",
    isFlagged: false,
    isHidden: false,
    flags: 0,
    likes: 22,
    replies: 2,
    likedBy: [
      {
        id: "like_025",
        name: "Hannah White",
        avatar: "https://i.pravatar.cc/150?u=hannah",
      },
      {
        id: "like_026",
        name: "Fiona Green",
        avatar: "https://i.pravatar.cc/150?u=fiona",
      },
    ],
    repliedBy: [
      {
        id: "rep_012",
        name: "Charlie Davis",
        avatar: "https://i.pravatar.cc/150?u=charlie",
        content: "I would love to see more tutorials too!",
        createdAt: new Date("2024-01-12T11:00:00"),
      },
    ],
    createdAt: new Date("2024-01-12T10:00:00"),
    updatedAt: new Date("2024-01-12T10:00:00"),
  },
  {
    id: "cmt_010",
    userId: "user_010",
    userName: "Hannah White",
    userEmail: "hannah.white@example.com",
    userAvatar: "https://i.pravatar.cc/150?u=hannah",
    videoId: "vid_002",
    videoTitle: "Elephant Dream - YouTube Video",
    content: "Inappropriate language used in this comment. Reported!",
    status: "flagged",
    isFlagged: true,
    isHidden: false,
    flags: 7,
    likes: 0,
    replies: 0,
    likedBy: [],
    repliedBy: [],
    createdAt: new Date("2024-01-12T11:30:00"),
    updatedAt: new Date("2024-01-12T15:00:00"),
  },
  {
    id: "cmt_011",
    userId: "user_011",
    userName: "Ian Thompson",
    userEmail: "ian.thompson@example.com",
    userAvatar: "https://i.pravatar.cc/150?u=ian",
    videoId: "vid_003",
    videoTitle: "Sintel - Sample Video",
    content: "Amazing character development and storytelling!",
    status: "active",
    isFlagged: false,
    isHidden: false,
    flags: 0,
    likes: 41,
    replies: 3,
    likedBy: [
      {
        id: "like_027",
        name: "Julia Adams",
        avatar: "https://i.pravatar.cc/150?u=julia",
      },
      {
        id: "like_028",
        name: "George Harris",
        avatar: "https://i.pravatar.cc/150?u=george",
      },
      {
        id: "like_029",
        name: "Edward Foster",
        avatar: "https://i.pravatar.cc/150?u=edward",
      },
      {
        id: "like_030",
        name: "Diana Evans",
        avatar: "https://i.pravatar.cc/150?u=diana",
      },
      {
        id: "like_031",
        name: "Jane Smith",
        avatar: "https://i.pravatar.cc/150?u=jane",
      },
    ],
    repliedBy: [
      {
        id: "rep_013",
        name: "Alice Brown",
        avatar: "https://i.pravatar.cc/150?u=alice",
        content: "The character arcs are so well written!",
        createdAt: new Date("2024-01-12T14:00:00"),
      },
      {
        id: "rep_014",
        name: "John Doe",
        avatar: "https://i.pravatar.cc/150?u=john",
        content: "One of the best storylines I've seen!",
        createdAt: new Date("2024-01-12T15:00:00"),
      },
    ],
    createdAt: new Date("2024-01-12T13:00:00"),
    updatedAt: new Date("2024-01-12T13:00:00"),
  },
  {
    id: "cmt_012",
    userId: "user_012",
    userName: "Julia Adams",
    userEmail: "julia.adams@example.com",
    userAvatar: "https://i.pravatar.cc/150?u=julia",
    videoId: "vid_004",
    videoTitle: "Tears of Steel - Sample Video",
    content: "SPAM: Buy now!!! Best deals!!! Click here!!!",
    status: "hidden",
    isFlagged: true,
    isHidden: true,
    flags: 15,
    likes: 0,
    replies: 0,
    likedBy: [],
    repliedBy: [],
    createdAt: new Date("2024-01-12T14:30:00"),
    updatedAt: new Date("2024-01-12T18:00:00"),
  },
];

export const mockUserProfiles: UserProfile[] = [
  {
    id: "user_001",
    name: "John Doe",
    email: "john.doe@example.com",
    avatar: "https://i.pravatar.cc/150?u=john",
    bio: "Video enthusiast and tech lover",
    location: "Johannesburg, South Africa",
    website: "https://johndoe.example.com",
    socialLinks: {
      twitter: "@johndoe",
      instagram: "@johndoe_official",
    },
    totalComments: 156,
    totalLikes: 2340,
    totalVideos: 12,
    joinedAt: new Date("2023-06-15"),
    lastActive: new Date("2024-01-15"),
    status: "active",
  },
  {
    id: "user_002",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    avatar: "https://i.pravatar.cc/150?u=jane",
    bio: "Film critic and animation fan",
    location: "Cape Town, South Africa",
    socialLinks: {
      youtube: "@janesmith",
    },
    totalComments: 89,
    totalLikes: 1890,
    totalVideos: 8,
    joinedAt: new Date("2023-08-20"),
    lastActive: new Date("2024-01-14"),
    status: "active",
  },
  {
    id: "user_003",
    name: "Bob Wilson",
    email: "bob.wilson@example.com",
    avatar: "https://i.pravatar.cc/150?u=bob",
    bio: "Content moderator",
    location: "Pretoria, South Africa",
    totalComments: 45,
    totalLikes: 670,
    totalVideos: 3,
    joinedAt: new Date("2023-10-10"),
    lastActive: new Date("2024-01-13"),
    status: "active",
  },
  {
    id: "user_004",
    name: "Alice Brown",
    email: "alice.brown@example.com",
    avatar: "https://i.pravatar.cc/150?u=alice",
    bio: "Graphic designer and animator",
    location: "Durban, South Africa",
    socialLinks: {
      instagram: "@alice_art",
      twitter: "@alicecreative",
    },
    totalComments: 234,
    totalLikes: 4500,
    totalVideos: 25,
    joinedAt: new Date("2023-03-05"),
    lastActive: new Date("2024-01-15"),
    status: "active",
  },
  {
    id: "user_005",
    name: "Charlie Davis",
    email: "charlie.davis@example.com",
    avatar: "https://i.pravatar.cc/150?u=charlie",
    bio: "Marketing specialist",
    location: "Johannesburg, South Africa",
    totalComments: 12,
    totalLikes: 45,
    totalVideos: 1,
    joinedAt: new Date("2024-01-05"),
    lastActive: new Date("2024-01-12"),
    status: "suspended",
  },
  {
    id: "user_006",
    name: "Diana Evans",
    email: "diana.evans@example.com",
    avatar: "https://i.pravatar.cc/150?u=diana",
    bio: "Movie buff and entertainment journalist",
    location: "Johannesburg, South Africa",
    website: "https://dianaevans.example.com",
    socialLinks: {
      twitter: "@dianaevans",
      youtube: "@dianareviews",
    },
    totalComments: 312,
    totalLikes: 5670,
    totalVideos: 45,
    joinedAt: new Date("2022-11-20"),
    lastActive: new Date("2024-01-15"),
    status: "active",
  },
  {
    id: "user_007",
    name: "Edward Foster",
    email: "edward.foster@example.com",
    avatar: "https://i.pravatar.cc/150?u=edward",
    bio: "Community moderator",
    location: "Port Elizabeth, South Africa",
    totalComments: 67,
    totalLikes: 890,
    totalVideos: 5,
    joinedAt: new Date("2023-07-15"),
    lastActive: new Date("2024-01-12"),
    status: "active",
  },
  {
    id: "user_008",
    name: "Fiona Green",
    email: "fiona.green@example.com",
    avatar: "https://i.pravatar.cc/150?u=fiona",
    bio: "Visual effects artist",
    location: "Cape Town, South Africa",
    website: "https://fionagreeneffects.example.com",
    socialLinks: {
      instagram: "@fionavfx",
      youtube: "@fionavfxstudio",
    },
    totalComments: 178,
    totalLikes: 3200,
    totalVideos: 18,
    joinedAt: new Date("2023-01-25"),
    lastActive: new Date("2024-01-14"),
    status: "active",
  },
  {
    id: "user_009",
    name: "George Harris",
    email: "george.harris@example.com",
    avatar: "https://i.pravatar.cc/150?u=george",
    bio: "Software developer and tech reviewer",
    location: "Johannesburg, South Africa",
    website: "https://georgeharris.example.com",
    socialLinks: {
      twitter: "@georgeharris",
      youtube: "@georgeharris_tech",
    },
    totalComments: 445,
    totalLikes: 7800,
    totalVideos: 67,
    joinedAt: new Date("2022-08-10"),
    lastActive: new Date("2024-01-15"),
    status: "active",
  },
  {
    id: "user_010",
    name: "Hannah White",
    email: "hannah.white@example.com",
    avatar: "https://i.pravatar.cc/150?u=hannah",
    bio: "Film student and aspiring director",
    location: "Johannesburg, South Africa",
    totalComments: 23,
    totalLikes: 340,
    totalVideos: 2,
    joinedAt: new Date("2023-12-01"),
    lastActive: new Date("2024-01-12"),
    status: "active",
  },
  {
    id: "user_011",
    name: "Ian Thompson",
    email: "ian.thompson@example.com",
    avatar: "https://i.pravatar.cc/150?u=ian",
    bio: "Indie filmmaker",
    location: "Durban, South Africa",
    website: "https://ianthompsonfilms.example.com",
    socialLinks: {
      instagram: "@ianfilms",
      youtube: "@ianthompsonfilms",
    },
    totalComments: 156,
    totalLikes: 2800,
    totalVideos: 15,
    joinedAt: new Date("2023-04-20"),
    lastActive: new Date("2024-01-13"),
    status: "active",
  },
  {
    id: "user_012",
    name: "Julia Adams",
    email: "julia.adams@example.com",
    avatar: "https://i.pravatar.cc/150?u=julia",
    bio: "Digital marketer",
    location: "Pretoria, South Africa",
    totalComments: 5,
    totalLikes: 12,
    totalVideos: 0,
    joinedAt: new Date("2024-01-10"),
    lastActive: new Date("2024-01-12"),
    status: "banned",
  },
];

export const mockActivityLogs: ActivityLog[] = [
  {
    id: "log_001",
    adminUserId: "admin_1",
    adminUserName: "TESE Admin",
    adminUserEmail: "admin@tese.com",
    action: "CREATE_USER",
    targetType: "user",
    targetId: "admin_2",
    targetName: "John Moderator",
    details: "Created new admin user with role: editor",
    ipAddress: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0",
    createdAt: new Date("2024-01-15T09:30:00"),
  },
  {
    id: "log_002",
    adminUserId: "admin_1",
    adminUserName: "TESE Admin",
    adminUserEmail: "admin@tese.com",
    action: "UPDATE_USER",
    targetType: "user",
    targetId: "admin_3",
    targetName: "Jane Editor",
    details: "Updated user role from editor to admin",
    ipAddress: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0",
    createdAt: new Date("2024-01-15T10:15:00"),
  },
  {
    id: "log_003",
    adminUserId: "admin_1",
    adminUserName: "TESE Admin",
    adminUserEmail: "admin@tese.com",
    action: "DEACTIVATE_USER",
    targetType: "user",
    targetId: "admin_4",
    targetName: "Bob Auditor",
    details: "Deactivated user account",
    ipAddress: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Safari/17.0",
    createdAt: new Date("2024-01-14T14:20:00"),
  },
  {
    id: "log_004",
    adminUserId: "admin_2",
    adminUserName: "John Moderator",
    adminUserEmail: "john@tese.com",
    action: "RESET_PASSWORD",
    targetType: "user",
    targetId: "admin_3",
    targetName: "Jane Editor",
    details: "Reset password for user",
    ipAddress: "192.168.1.101",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Edge/120.0.0.0",
    createdAt: new Date("2024-01-14T11:45:00"),
  },
  {
    id: "log_005",
    adminUserId: "admin_1",
    adminUserName: "TESE Admin",
    adminUserEmail: "admin@tese.com",
    action: "UPDATE_FEE",
    targetType: "fee",
    targetId: "fee_1",
    targetName: "Platform Fee",
    details: "Updated platform fee from 5% to 7%",
    ipAddress: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0",
    createdAt: new Date("2024-01-13T16:30:00"),
  },
  {
    id: "log_006",
    adminUserId: "admin_1",
    adminUserName: "TESE Admin",
    adminUserEmail: "admin@tese.com",
    action: "CREATE_ROLE",
    targetType: "role",
    targetId: "role_1",
    targetName: "Content Moderator",
    details: "Created new role with permissions: videos, comments",
    ipAddress: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0",
    createdAt: new Date("2024-01-12T08:00:00"),
  },
  {
    id: "log_007",
    adminUserId: "admin_3",
    adminUserName: "Jane Editor",
    adminUserEmail: "jane@tese.com",
    action: "UPDATE_SETTINGS",
    targetType: "settings",
    targetId: "settings_1",
    targetName: "General Settings",
    details: "Updated site title and description",
    ipAddress: "192.168.1.102",
    userAgent:
      "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) Safari/17.0",
    createdAt: new Date("2024-01-11T13:25:00"),
  },
  {
    id: "log_008",
    adminUserId: "admin_1",
    adminUserName: "TESE Admin",
    adminUserEmail: "admin@tese.com",
    action: "BULK_ACTIVATE",
    targetType: "user",
    targetId: "bulk_users",
    targetName: "5 users",
    details: "Bulk activated 5 deactivated users",
    ipAddress: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0",
    createdAt: new Date("2024-01-10T10:00:00"),
  },
];
