import type {
  User,
  Transaction,
  Creator,
  Video,
  Category,
  FeaturedCreator,
  Device,
  DashboardStats,
  ChartDataPoint,
  DashboardOverview,
} from "@/types";

export const mockUsers: User[] = [
  {
    id: "1",
    email: "admin@tese.com",
    name: "TESE Admin",
    role: "admin",
    avatar: "",
    createdAt: new Date("2024-01-01"),
    lastLogin: new Date(),
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: "txn_001",
    userId: "user_001",
    userName: "John Doe",
    amount: 29.99,
    currency: "USD",
    type: "payment",
    status: "completed",
    description: "Video subscription - Premium Plan",
    createdAt: new Date("2024-01-15T10:30:00"),
  },
  {
    id: "txn_002",
    userId: "user_002",
    userName: "Jane Smith",
    amount: 14.99,
    currency: "USD",
    type: "payment",
    status: "pending",
    description: "Video purchase - Tutorial Series",
    createdAt: new Date("2024-01-15T11:45:00"),
  },
  {
    id: "txn_003",
    userId: "user_003",
    userName: "Bob Wilson",
    amount: 99.99,
    currency: "USD",
    type: "withdrawal",
    status: "completed",
    description: "Creator payout - January earnings",
    createdAt: new Date("2024-01-14T15:20:00"),
  },
  {
    id: "txn_004",
    userId: "user_001",
    userName: "John Doe",
    amount: 29.99,
    currency: "USD",
    type: "refund",
    status: "refunded",
    description: "Refund - Duplicate purchase",
    createdAt: new Date("2024-01-13T09:15:00"),
  },
  {
    id: "txn_005",
    userId: "user_004",
    userName: "Alice Brown",
    amount: 49.99,
    currency: "USD",
    type: "payment",
    status: "flagged",
    description: "Video subscription - Annual Plan",
    createdAt: new Date("2024-01-15T14:00:00"),
  },
  {
    id: "txn_006",
    userId: "user_005",
    userName: "Charlie Davis",
    amount: 19.99,
    currency: "USD",
    type: "payment",
    status: "failed",
    description: "Video purchase - Masterclass",
    createdAt: new Date("2024-01-15T16:30:00"),
  },
  {
    id: "txn_007",
    userId: "user_006",
    userName: "Diana Evans",
    amount: 250.0,
    currency: "USD",
    type: "deposit",
    status: "completed",
    description: "Wallet deposit",
    createdAt: new Date("2024-01-12T08:00:00"),
  },
  {
    id: "txn_008",
    userId: "user_002",
    userName: "Jane Smith",
    amount: 75.0,
    currency: "USD",
    type: "withdrawal",
    status: "pending",
    description: "Creator payout - Week 2",
    createdAt: new Date("2024-01-15T12:00:00"),
  },
];

export const mockCreators: Creator[] = [
  {
    id: "cr_001",
    name: "Tech Master",
    email: "techmaster@example.com",
    avatar: "",
    channelId: "ch_001",
    channelName: "TechMaster Official",
    status: "active",
    onlineStatus: "online",
    lastSeen: new Date(),
    totalVideos: 156,
    totalViews: 2500000,
    totalEarnings: 15000,
    smatPayMerchantId: "SP_MERCHANT_001",
    smatPayStatus: "verified",
    createdAt: new Date("2023-06-15"),
  },
  {
    id: "cr_002",
    name: "Cooking Expert",
    email: "cookingexpert@example.com",
    avatar: "",
    channelId: "ch_002",
    channelName: "Chef's Kitchen",
    status: "active",
    onlineStatus: "away",
    lastSeen: new Date(Date.now() - 3600000),
    totalVideos: 89,
    totalViews: 1800000,
    totalEarnings: 12000,
    smatPayMerchantId: "SP_MERCHANT_002",
    smatPayStatus: "verified",
    createdAt: new Date("2023-08-20"),
  },
  {
    id: "cr_003",
    name: "Fitness Pro",
    email: "fitnesspro@example.com",
    avatar: "",
    channelId: "ch_003",
    channelName: "FitLife Studio",
    status: "pending",
    onlineStatus: "offline",
    lastSeen: new Date(Date.now() - 86400000),
    totalVideos: 45,
    totalViews: 500000,
    totalEarnings: 3500,
    smatPayMerchantId: "SP_MERCHANT_003",
    smatPayStatus: "pending",
    createdAt: new Date("2023-11-10"),
  },
  {
    id: "cr_004",
    name: "Music Channel",
    email: "musicchannel@example.com",
    avatar: "",
    channelId: "ch_004",
    channelName: "Melody Beats",
    status: "suspended",
    onlineStatus: "offline",
    lastSeen: new Date(Date.now() - 172800000),
    totalVideos: 200,
    totalViews: 5000000,
    totalEarnings: 25000,
    createdAt: new Date("2023-03-01"),
  },
  {
    id: "cr_005",
    name: "Gaming Hub",
    email: "gaminghub@example.com",
    avatar: "",
    channelId: "ch_005",
    channelName: "Pro Gaming Zone",
    status: "active",
    onlineStatus: "online",
    lastSeen: new Date(),
    totalVideos: 312,
    totalViews: 8000000,
    totalEarnings: 45000,
    smatPayMerchantId: "SP_MERCHANT_005",
    smatPayStatus: "verified",
    createdAt: new Date("2023-01-15"),
  },
  {
    id: "cr_006",
    name: "Education Plus",
    email: "educationplus@example.com",
    avatar: "",
    channelId: "ch_006",
    channelName: "Learn Everyday",
    status: "active",
    onlineStatus: "away",
    lastSeen: new Date(Date.now() - 7200000),
    totalVideos: 78,
    totalViews: 950000,
    totalEarnings: 8000,
    smatPayMerchantId: "SP_MERCHANT_006",
    smatPayStatus: "verified",
    createdAt: new Date("2023-09-05"),
  },
];

export const mockVideos: Video[] = [
  {
    id: "vid_001",
    title: "Complete React Tutorial for Beginners",
    description:
      "Learn React from scratch with this comprehensive tutorial covering hooks, components, and more.",
    thumbnail: "",
    duration: 7200,
    creatorId: "cr_001",
    creatorName: "Tech Master",
    categoryId: "cat_001",
    categoryName: "Technology",
    status: "published",
    isFeatured: true,
    isBanner: false,
    isPaid: false,
    views: 150000,
    likes: 8500,
    comments: 450,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    id: "vid_002",
    title: "Italian Cooking Masterclass",
    description:
      "Master authentic Italian cuisine with professional chef techniques.",
    thumbnail: "",
    duration: 5400,
    creatorId: "cr_002",
    creatorName: "Cooking Expert",
    categoryId: "cat_002",
    categoryName: "Food & Cooking",
    status: "published",
    isFeatured: false,
    isBanner: true,
    isPaid: true,
    price: 29.99,
    views: 85000,
    likes: 4200,
    comments: 280,
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    id: "vid_003",
    title: "30-Day Fitness Challenge",
    description:
      "Transform your body with this intensive 30-day workout program.",
    thumbnail: "",
    duration: 3600,
    creatorId: "cr_003",
    creatorName: "Fitness Pro",
    categoryId: "cat_003",
    categoryName: "Health & Fitness",
    status: "pending",
    isFeatured: false,
    isBanner: false,
    isPaid: true,
    price: 19.99,
    views: 0,
    likes: 0,
    comments: 0,
    createdAt: new Date("2024-01-14"),
    updatedAt: new Date("2024-01-14"),
  },
  {
    id: "vid_004",
    title: "Music Production Fundamentals",
    description:
      "Learn the basics of music production with professional software.",
    thumbnail: "",
    duration: 9000,
    creatorId: "cr_004",
    creatorName: "Music Channel",
    categoryId: "cat_004",
    categoryName: "Music",
    status: "suspended",
    isFeatured: false,
    isBanner: false,
    isPaid: false,
    views: 250000,
    likes: 12000,
    comments: 890,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-13"),
  },
  {
    id: "vid_005",
    title: "Pro Gaming Strategies",
    description:
      "Competitive gaming tips and strategies from professional players.",
    thumbnail: "",
    duration: 2700,
    creatorId: "cr_005",
    creatorName: "Gaming Hub",
    categoryId: "cat_005",
    categoryName: "Gaming",
    status: "published",
    isFeatured: true,
    isBanner: true,
    isPaid: false,
    views: 500000,
    likes: 25000,
    comments: 1500,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-11"),
  },
  {
    id: "vid_006",
    title: "Mathematics for Everyone",
    description: "Understanding complex mathematical concepts made simple.",
    thumbnail: "",
    duration: 4500,
    creatorId: "cr_006",
    creatorName: "Education Plus",
    categoryId: "cat_006",
    categoryName: "Education",
    status: "published",
    isFeatured: false,
    isBanner: false,
    isPaid: true,
    price: 14.99,
    views: 45000,
    likes: 2100,
    comments: 120,
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-13"),
  },
];

export const mockCategories: Category[] = [
  {
    id: "cat_001",
    name: "Technology",
    slug: "technology",
    description: "Tech tutorials, reviews, and guides",
    icon: "Monitor",
    color: "#3B82F6",
    videoCount: 1250,
    isActive: true,
    createdAt: new Date("2023-01-01"),
  },
  {
    id: "cat_002",
    name: "Food & Cooking",
    slug: "food-cooking",
    description: "Recipes, cooking techniques, and food culture",
    icon: "Utensils",
    color: "#F59E0B",
    videoCount: 890,
    isActive: true,
    createdAt: new Date("2023-01-15"),
  },
  {
    id: "cat_003",
    name: "Health & Fitness",
    slug: "health-fitness",
    description: "Workouts, nutrition, and wellness tips",
    icon: "Heart",
    color: "#10B981",
    videoCount: 720,
    isActive: true,
    createdAt: new Date("2023-02-01"),
  },
  {
    id: "cat_004",
    name: "Music",
    slug: "music",
    description: "Music tutorials, performances, and production",
    icon: "Music",
    color: "#8B5CF6",
    videoCount: 1560,
    isActive: true,
    createdAt: new Date("2023-02-15"),
  },
  {
    id: "cat_005",
    name: "Gaming",
    slug: "gaming",
    description: "Gameplay, reviews, and gaming culture",
    icon: "Gamepad2",
    color: "#EF4444",
    videoCount: 2100,
    isActive: true,
    createdAt: new Date("2023-03-01"),
  },
  {
    id: "cat_006",
    name: "Education",
    slug: "education",
    description: "Educational content and learning resources",
    icon: "GraduationCap",
    color: "#06B6D4",
    videoCount: 650,
    isActive: true,
    createdAt: new Date("2023-03-15"),
  },
  {
    id: "cat_007",
    name: "Entertainment",
    slug: "entertainment",
    description: "Movies, TV shows, and entertainment news",
    icon: "Film",
    color: "#EC4899",
    videoCount: 980,
    isActive: false,
    createdAt: new Date("2023-04-01"),
  },
];

export const mockFeaturedCreators: FeaturedCreator[] = [
  {
    id: "fc_001",
    creatorId: "cr_001",
    creator: mockCreators[0],
    position: 1,
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "fc_002",
    creatorId: "cr_005",
    creator: mockCreators[4],
    position: 2,
    isActive: true,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "fc_003",
    creatorId: "cr_002",
    creator: mockCreators[1],
    position: 3,
    isActive: true,
    createdAt: new Date("2024-01-10"),
  },
];

export const mockDevices: Device[] = [
  {
    id: "dev_001",
    userId: "user_001",
    deviceType: "desktop",
    browser: "Chrome 120",
    os: "Windows 11",
    ipAddress: "192.168.1.100",
    location: {
      country: "United States",
      city: "New York",
      timezone: "America/New_York",
    },
    lastActive: new Date(),
    isCurrentSession: true,
  },
  {
    id: "dev_002",
    userId: "user_001",
    deviceType: "mobile",
    browser: "Safari iOS 17",
    os: "iOS 17.2",
    ipAddress: "192.168.1.101",
    location: {
      country: "United States",
      city: "New York",
      timezone: "America/New_York",
    },
    lastActive: new Date(Date.now() - 3600000),
    isCurrentSession: false,
  },
  {
    id: "dev_003",
    userId: "user_001",
    deviceType: "tablet",
    browser: "Firefox 121",
    os: "Android 14",
    ipAddress: "192.168.1.102",
    location: {
      country: "United States",
      city: "New York",
      timezone: "America/New_York",
    },
    lastActive: new Date(Date.now() - 7200000),
    isCurrentSession: false,
  },
];

export const mockDashboardStats: DashboardStats = {
  totalTransactions: 12458,
  totalRevenue: 285420.5,
  totalCreators: 1250,
  totalChannels: 890,
  totalVideos: 15680,
  totalViews: 45000000,
  dailyVisitors: 12580,
  dailyViews: 45800,
  activeChannels: 756,
  transactionGrowth: 12.5,
  revenueGrowth: 8.3,
  creatorGrowth: 15.2,
  videoGrowth: 22.1,
};

export const mockTransactionChartData: ChartDataPoint[] = [
  { date: "2024-01-09", value: 4200, label: "Mon" },
  { date: "2024-01-10", value: 5100, label: "Tue" },
  { date: "2024-01-11", value: 4800, label: "Wed" },
  { date: "2024-01-12", value: 6200, label: "Thu" },
  { date: "2024-01-13", value: 5800, label: "Fri" },
  { date: "2024-01-14", value: 7100, label: "Sat" },
  { date: "2024-01-15", value: 6500, label: "Sun" },
];

export const mockRevenueChartData: ChartDataPoint[] = [
  { date: "2024-01-09", value: 12500 },
  { date: "2024-01-10", value: 15800 },
  { date: "2024-01-11", value: 14200 },
  { date: "2024-01-12", value: 18900 },
  { date: "2024-01-13", value: 17500 },
  { date: "2024-01-14", value: 21000 },
  { date: "2024-01-15", value: 19200 },
];

export const mockVisitorChartData: ChartDataPoint[] = [
  { date: "00:00", value: 1200 },
  { date: "04:00", value: 800 },
  { date: "08:00", value: 3500 },
  { date: "12:00", value: 8200 },
  { date: "16:00", value: 7500 },
  { date: "20:00", value: 6800 },
  { date: "23:59", value: 2100 },
];

export const mockGrowthChartData: ChartDataPoint[] = [
  { date: "Week 1", value: 450 },
  { date: "Week 2", value: 520 },
  { date: "Week 3", value: 610 },
  { date: "Week 4", value: 780 },
];

export const mockOverviewData: DashboardOverview = {
  transactions: [
    { label: "Jan", value: 4200 },
    { label: "Feb", value: 5100 },
    { label: "Mar", value: 4800 },
    { label: "Apr", value: 6200 },
    { label: "May", value: 5800 },
    { label: "Jun", value: 7100 },
    { label: "Jul", value: 6500 },
    { label: "Aug", value: 8200 },
    { label: "Sep", value: 7800 },
    { label: "Oct", value: 9200 },
    { label: "Nov", value: 8900 },
    { label: "Dec", value: 10500 },
  ],
  creators: [
    { label: "Jan", value: 120 },
    { label: "Feb", value: 145 },
    { label: "Mar", value: 168 },
    { label: "Apr", value: 192 },
    { label: "May", value: 215 },
    { label: "Jun", value: 248 },
    { label: "Jul", value: 275 },
    { label: "Aug", value: 310 },
    { label: "Sep", value: 345 },
    { label: "Oct", value: 380 },
    { label: "Nov", value: 420 },
    { label: "Dec", value: 465 },
  ],
  traffic: [
    { label: "Jan", value: 12500 },
    { label: "Feb", value: 15800 },
    { label: "Mar", value: 14200 },
    { label: "Apr", value: 18900 },
    { label: "May", value: 17500 },
    { label: "Jun", value: 21000 },
    { label: "Jul", value: 19200 },
    { label: "Aug", value: 22500 },
    { label: "Sep", value: 24800 },
    { label: "Oct", value: 27200 },
    { label: "Nov", value: 29500 },
    { label: "Dec", value: 32000 },
  ],
  totals: {
    revenue: 285420.5,
    creators: 1250,
    videos: 15680,
    channels: 890,
    views: 45000000,
    visitors: 125800,
  },
};
