import type {
  User,
  Transaction,
  Creator,
  Video,
  Category,
  FeaturedCreator,
  Device,
  DashboardStats,
  ChartDataPoint,
  DashboardOverview,
  PayoutRequest,
  KYCUser,
  AdminUser,
  Role,
  Permission,
  FeeConfiguration,
} from "@/types";

export const mockUsers: User[] = [
  {
    id: "1",
    email: "admin@tese.com",
    name: "TESE Admin",
    role: "admin",
    avatar: "",
    createdAt: new Date("2024-01-01"),
    lastLogin: new Date(),
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: "txn_001",
    userId: "user_001",
    userName: "John Doe",
    amount: 29.99,
    currency: "USD",
    type: "payment",
    status: "completed",
    description: "Video subscription - Premium Plan",
    createdAt: new Date("2024-01-15T10:30:00"),
  },
  {
    id: "txn_002",
    userId: "user_002",
    userName: "Jane Smith",
    amount: 14.99,
    currency: "USD",
    type: "payment",
    status: "pending",
    description: "Video purchase - Tutorial Series",
    createdAt: new Date("2024-01-15T11:45:00"),
  },
  {
    id: "txn_003",
    userId: "user_003",
    userName: "Bob Wilson",
    amount: 99.99,
    currency: "USD",
    type: "withdrawal",
    status: "completed",
    description: "Creator payout - January earnings",
    createdAt: new Date("2024-01-14T15:20:00"),
  },
  {
    id: "txn_004",
    userId: "user_001",
    userName: "John Doe",
    amount: 29.99,
    currency: "USD",
    type: "refund",
    status: "refunded",
    description: "Refund - Duplicate purchase",
    createdAt: new Date("2024-01-13T09:15:00"),
  },
  {
    id: "txn_005",
    userId: "user_004",
    userName: "Alice Brown",
    amount: 49.99,
    currency: "USD",
    type: "payment",
    status: "flagged",
    description: "Video subscription - Annual Plan",
    createdAt: new Date("2024-01-15T14:00:00"),
  },
  {
    id: "txn_006",
    userId: "user_005",
    userName: "Charlie Davis",
    amount: 19.99,
    currency: "USD",
    type: "payment",
    status: "failed",
    description: "Video purchase - Masterclass",
    createdAt: new Date("2024-01-15T16:30:00"),
  },
  {
    id: "txn_007",
    userId: "user_006",
    userName: "Diana Evans",
    amount: 250.0,
    currency: "USD",
    type: "deposit",
    status: "completed",
    description: "Wallet deposit",
    createdAt: new Date("2024-01-12T08:00:00"),
  },
  {
    id: "txn_008",
    userId: "user_002",
    userName: "Jane Smith",
    amount: 75.0,
    currency: "USD",
    type: "withdrawal",
    status: "pending",
    description: "Creator payout - Week 2",
    createdAt: new Date("2024-01-15T12:00:00"),
  },
];

export const mockCreators: Creator[] = [
  {
    id: "cr_001",
    firstName: "Tech",
    lastName: "Master",
    email: "techmaster@example.com",
    phone: "+27 82 123 4567",
    avatar: "https://i.pravatar.cc/150?u=techmaster",
    coverImage: "",
    channelId: "ch_001",
    channelName: "TechMaster Official",
    channelUrl: "https://tese.com/channel/techmaster",
    status: "active",
    onlineStatus: "online",
    lastSeen: new Date(),
    totalVideos: 156,
    totalViews: 2500000,
    totalEarnings: 15000,
    categories: ["Technology", "Education"],
    
    // Address Information
    address: "123 Tech Street",
    city: "Johannesburg",
    province: "Gauteng",
    country: "South Africa",
    postalCode: "2001",
    
    // Identity Verification
    idType: "national_id",
    idNumber: "1234567890123",
    idCopyUrl: "/docs/id_cr_001.pdf",
    proofOfResidenceUrl: "/docs/por_cr_001.pdf",
    
    // Banking Information
    bankName: "First National Bank",
    bankAccountNumber: "1234567890",
    bankBranch: "FNB001",
    accountHolderName: "Tech Master",
    
    // SmatPay Integration
    smatPayMerchantId: "SP_MERCHANT_001",
    smatPayStatus: "verified",
    
    createdAt: new Date("2023-06-15"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "cr_002",
    firstName: "Cooking",
    lastName: "Expert",
    email: "cookingexpert@example.com",
    phone: "+27 83 234 5678",
    avatar: "https://i.pravatar.cc/150?u=cookingexpert",
    coverImage: "",
    channelId: "ch_002",
    channelName: "Chef's Kitchen",
    channelUrl: "https://tese.com/channel/cookingexpert",
    status: "active",
    onlineStatus: "away",
    lastSeen: new Date(Date.now() - 3600000),
    totalVideos: 89,
    totalViews: 1800000,
    totalEarnings: 12000,
    categories: ["Food & Cooking", "Lifestyle"],
    
    // Address Information
    address: "456 Food Avenue",
    city: "Cape Town",
    province: "Western Cape",
    country: "South Africa",
    postalCode: "8001",
    
    // Identity Verification
    idType: "national_id",
    idNumber: "2345678901234",
    idCopyUrl: "/docs/id_cr_002.pdf",
    proofOfResidenceUrl: "/docs/por_cr_002.pdf",
    
    // Banking Information
    bankName: "Standard Bank",
    bankAccountNumber: "2345678901",
    bankBranch: "STD001",
    accountHolderName: "Cooking Expert",
    
    // SmatPay Integration
    smatPayMerchantId: "SP_MERCHANT_002",
    smatPayStatus: "verified",
    
    createdAt: new Date("2023-08-20"),
    updatedAt: new Date("2024-01-02"),
  },
  {
    id: "cr_003",
    firstName: "Fitness",
    lastName: "Pro",
    email: "fitnesspro@example.com",
    phone: "+27 84 345 6789",
    avatar: "https://i.pravatar.cc/150?u=fitnesspro",
    coverImage: "",
    channelId: "ch_003",
    channelName: "FitLife Studio",
    channelUrl: "https://tese.com/channel/fitnesspro",
    status: "pending",
    onlineStatus: "offline",
    lastSeen: new Date(Date.now() - 86400000),
    totalVideos: 45,
    totalViews: 500000,
    totalEarnings: 3500,
    categories: ["Health & Fitness", "Sports"],
    
    // Address Information
    address: "789 Health Road",
    city: "Durban",
    province: "KwaZulu-Natal",
    country: "South Africa",
    postalCode: "4001",
    
    // Identity Verification
    idType: "passport",
    idNumber: "A12345678",
    idCopyUrl: "/docs/id_cr_003.pdf",
    proofOfResidenceUrl: "/docs/por_cr_003.pdf",
    
    // Banking Information
    bankName: "Absa Bank",
    bankAccountNumber: "3456789012",
    bankBranch: "ABSA001",
    accountHolderName: "Fitness Pro",
    
    // SmatPay Integration
    smatPayMerchantId: "SP_MERCHANT_003",
    smatPayStatus: "pending",
    
    createdAt: new Date("2023-11-10"),
    updatedAt: new Date("2024-01-03"),
  },
  {
    id: "cr_004",
    firstName: "Music",
    lastName: "Channel",
    email: "musicchannel@example.com",
    phone: "+27 85 456 7890",
    avatar: "https://i.pravatar.cc/150?u=musicchannel",
    coverImage: "",
    channelId: "ch_004",
    channelName: "Melody Beats",
    channelUrl: "https://tese.com/channel/melodybeats",
    status: "suspended",
    onlineStatus: "offline",
    lastSeen: new Date(Date.now() - 172800000),
    totalVideos: 200,
    totalViews: 5000000,
    totalEarnings: 25000,
    categories: ["Music", "Entertainment"],
    
    // Address Information
    address: "321 Music Lane",
    city: "Pretoria",
    province: "Gauteng",
    country: "South Africa",
    postalCode: "0002",
    
    // Identity Verification
    idType: "national_id",
    idNumber: "3456789012345",
    idCopyUrl: "/docs/id_cr_004.pdf",
    proofOfResidenceUrl: "/docs/por_cr_004.pdf",
    
    // Banking Information
    bankName: "Nedbank",
    bankAccountNumber: "4567890123",
    bankBranch: "NED001",
    accountHolderName: "Music Channel",
    
    // SmatPay Integration
    smatPayMerchantId: "",
    smatPayStatus: undefined,
    
    createdAt: new Date("2023-03-01"),
    updatedAt: new Date("2024-01-04"),
  },
  {
    id: "cr_005",
    firstName: "Gaming",
    lastName: "Hub",
    email: "gaminghub@example.com",
    phone: "+27 86 567 8901",
    avatar: "https://i.pravatar.cc/150?u=gaminghub",
    coverImage: "",
    channelId: "ch_005",
    channelName: "Pro Gaming Zone",
    channelUrl: "https://tese.com/channel/progaming",
    status: "active",
    onlineStatus: "online",
    lastSeen: new Date(),
    totalVideos: 312,
    totalViews: 8000000,
    totalEarnings: 45000,
    categories: ["Gaming", "Entertainment"],
    
    // Address Information
    address: "555 Player Street",
    city: "Johannesburg",
    province: "Gauteng",
    country: "South Africa",
    postalCode: "2196",
    
    // Identity Verification
    idType: "drivers_license",
    idNumber: "D1234567",
    idCopyUrl: "/docs/id_cr_005.pdf",
    proofOfResidenceUrl: "/docs/por_cr_005.pdf",
    
    // Banking Information
    bankName: "Capitec Bank",
    bankAccountNumber: "5678901234",
    bankBranch: "CAP001",
    accountHolderName: "Gaming Hub",
    
    // SmatPay Integration
    smatPayMerchantId: "SP_MERCHANT_005",
    smatPayStatus: "verified",
    
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-01-05"),
  },
];

export const mockVideos: Video[] = [
  {
    id: "vid_001",
    title: "Complete React Tutorial for Beginners",
    description:
      "Learn React from scratch with this comprehensive tutorial covering hooks, components, and more.",
    thumbnail: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=320&h=180&fit=crop",
    duration: 7200,
    creatorId: "cr_001",
    creatorName: "Tech Master",
    categoryId: "cat_001",
    categoryName: "Technology",
    status: "published",
    isFeatured: true,
    isBanner: false,
    isPaid: false,
    views: 150000,
    likes: 8500,
    comments: 450,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    id: "vid_002",
    title: "Italian Cooking Masterclass",
    description:
      "Master authentic Italian cuisine with professional chef techniques.",
    thumbnail: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=320&h=180&fit=crop",
    duration: 5400,
    creatorId: "cr_002",
    creatorName: "Cooking Expert",
    categoryId: "cat_002",
    categoryName: "Food & Cooking",
    status: "published",
    isFeatured: false,
    isBanner: true,
    isPaid: true,
    price: 29.99,
    views: 85000,
    likes: 4200,
    comments: 280,
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    id: "vid_003",
    title: "30-Day Fitness Challenge",
    description:
      "Transform your body with this intensive 30-day workout program.",
    thumbnail: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=320&h=180&fit=crop",
    duration: 3600,
    creatorId: "cr_003",
    creatorName: "Fitness Pro",
    categoryId: "cat_003",
    categoryName: "Health & Fitness",
    status: "pending",
    isFeatured: false,
    isBanner: false,
    isPaid: true,
    price: 19.99,
    views: 0,
    likes: 0,
    comments: 0,
    createdAt: new Date("2024-01-14"),
    updatedAt: new Date("2024-01-14"),
  },
  {
    id: "vid_004",
    title: "Music Production Fundamentals",
    description:
      "Learn the basics of music production with professional software.",
    thumbnail: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=320&h=180&fit=crop",
    duration: 9000,
    creatorId: "cr_004",
    creatorName: "Music Channel",
    categoryId: "cat_004",
    categoryName: "Music",
    status: "suspended",
    isFeatured: false,
    isBanner: false,
    isPaid: false,
    views: 250000,
    likes: 12000,
    comments: 890,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-13"),
  },
  {
    id: "vid_005",
    title: "Pro Gaming Strategies",
    description:
      "Competitive gaming tips and strategies from professional players.",
    thumbnail: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=320&h=180&fit=crop",
    duration: 2700,
    creatorId: "cr_005",
    creatorName: "Gaming Hub",
    categoryId: "cat_005",
    categoryName: "Gaming",
    status: "published",
    isFeatured: true,
    isBanner: true,
    isPaid: false,
    views: 500000,
    likes: 25000,
    comments: 1500,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-11"),
  },
  {
    id: "vid_006",
    title: "Mathematics for Everyone",
    description: "Understanding complex mathematical concepts made simple.",
    thumbnail: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=320&h=180&fit=crop",
    duration: 4500,
    creatorId: "cr_006",
    creatorName: "Education Plus",
    categoryId: "cat_006",
    categoryName: "Education",
    status: "published",
    isFeatured: false,
    isBanner: false,
    isPaid: true,
    price: 14.99,
    views: 45000,
    likes: 2100,
    comments: 120,
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-13"),
  },
];

export const mockCategories: Category[] = [
  {
    id: "cat_001",
    name: "Technology",
    slug: "technology",
    description: "Tech tutorials, reviews, and guides",
    icon: "Monitor",
    color: "#3B82F6",
    videoCount: 1250,
    isActive: true,
    createdAt: new Date("2023-01-01"),
  },
  {
    id: "cat_002",
    name: "Food & Cooking",
    slug: "food-cooking",
    description: "Recipes, cooking techniques, and food culture",
    icon: "Utensils",
    color: "#F59E0B",
    videoCount: 890,
    isActive: true,
    createdAt: new Date("2023-01-15"),
  },
  {
    id: "cat_003",
    name: "Health & Fitness",
    slug: "health-fitness",
    description: "Workouts, nutrition, and wellness tips",
    icon: "Heart",
    color: "#10B981",
    videoCount: 720,
    isActive: true,
    createdAt: new Date("2023-02-01"),
  },
  {
    id: "cat_004",
    name: "Music",
    slug: "music",
    description: "Music tutorials, performances, and production",
    icon: "Music",
    color: "#8B5CF6",
    videoCount: 1560,
    isActive: true,
    createdAt: new Date("2023-02-15"),
  },
  {
    id: "cat_005",
    name: "Gaming",
    slug: "gaming",
    description: "Gameplay, reviews, and gaming culture",
    icon: "Gamepad2",
    color: "#EF4444",
    videoCount: 2100,
    isActive: true,
    createdAt: new Date("2023-03-01"),
  },
  {
    id: "cat_006",
    name: "Education",
    slug: "education",
    description: "Educational content and learning resources",
    icon: "GraduationCap",
    color: "#06B6D4",
    videoCount: 650,
    isActive: true,
    createdAt: new Date("2023-03-15"),
  },
  {
    id: "cat_007",
    name: "Entertainment",
    slug: "entertainment",
    description: "Movies, TV shows, and entertainment news",
    icon: "Film",
    color: "#EC4899",
    videoCount: 980,
    isActive: false,
    createdAt: new Date("2023-04-01"),
  },
];

export const mockFeaturedCreators: FeaturedCreator[] = [
  {
    id: "fc_001",
    creatorId: "cr_001",
    creator: mockCreators[0],
    position: 1,
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "fc_002",
    creatorId: "cr_005",
    creator: mockCreators[4],
    position: 2,
    isActive: true,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "fc_003",
    creatorId: "cr_002",
    creator: mockCreators[1],
    position: 3,
    isActive: true,
    createdAt: new Date("2024-01-10"),
  },
];

export const mockDevices: Device[] = [
  {
    id: "dev_001",
    userId: "user_001",
    deviceType: "desktop",
    browser: "Chrome 120",
    os: "Windows 11",
    ipAddress: "192.168.1.100",
    location: {
      country: "United States",
      city: "New York",
      timezone: "America/New_York",
    },
    lastActive: new Date(),
    isCurrentSession: true,
    isBlocked: false
  },
  {
    id: "dev_002",
    userId: "user_001",
    deviceType: "mobile",
    browser: "Safari iOS 17",
    os: "iOS 17.2",
    ipAddress: "192.168.1.101",
    location: {
      country: "United States",
      city: "New York",
      timezone: "America/New_York",
    },
    lastActive: new Date(Date.now() - 3600000),
    isCurrentSession: false,
    isBlocked: false
  },
  {
    id: "dev_003",
    userId: "user_001",
    deviceType: "tablet",
    browser: "Firefox 121",
    os: "Android 14",
    ipAddress: "192.168.1.102",
    location: {
      country: "United States",
      city: "New York",
      timezone: "America/New_York",
    },
    lastActive: new Date(Date.now() - 7200000),
    isCurrentSession: false,
    isBlocked: false
  },
];

export const mockDashboardStats: DashboardStats = {
  totalTransactions: 12458,
  totalRevenue: 285420.5,
  totalCreators: 1250,
  totalChannels: 890,
  totalVideos: 15680,
  totalViews: 45000000,
  dailyVisitors: 12580,
  dailyViews: 45800,
  activeChannels: 756,
  transactionGrowth: 12.5,
  revenueGrowth: 8.3,
  creatorGrowth: 15.2,
  videoGrowth: 22.1,
};

export const mockTransactionChartData: ChartDataPoint[] = [
  { date: "2024-01-09", value: 4200, label: "Mon" },
  { date: "2024-01-10", value: 5100, label: "Tue" },
  { date: "2024-01-11", value: 4800, label: "Wed" },
  { date: "2024-01-12", value: 6200, label: "Thu" },
  { date: "2024-01-13", value: 5800, label: "Fri" },
  { date: "2024-01-14", value: 7100, label: "Sat" },
  { date: "2024-01-15", value: 6500, label: "Sun" },
];

export const mockRevenueChartData: ChartDataPoint[] = [
  { date: "2024-01-09", value: 12500 },
  { date: "2024-01-10", value: 15800 },
  { date: "2024-01-11", value: 14200 },
  { date: "2024-01-12", value: 18900 },
  { date: "2024-01-13", value: 17500 },
  { date: "2024-01-14", value: 21000 },
  { date: "2024-01-15", value: 19200 },
];

export const mockVisitorChartData: ChartDataPoint[] = [
  { date: "00:00", value: 1200 },
  { date: "04:00", value: 800 },
  { date: "08:00", value: 3500 },
  { date: "12:00", value: 8200 },
  { date: "16:00", value: 7500 },
  { date: "20:00", value: 6800 },
  { date: "23:59", value: 2100 },
];

export const mockGrowthChartData: ChartDataPoint[] = [
  { date: "Week 1", value: 450 },
  { date: "Week 2", value: 520 },
  { date: "Week 3", value: 610 },
  { date: "Week 4", value: 780 },
];

export const mockOverviewData: DashboardOverview = {
  transactions: [
    { label: "Jan", value: 4200 },
    { label: "Feb", value: 5100 },
    { label: "Mar", value: 4800 },
    { label: "Apr", value: 6200 },
    { label: "May", value: 5800 },
    { label: "Jun", value: 7100 },
    { label: "Jul", value: 6500 },
    { label: "Aug", value: 8200 },
    { label: "Sep", value: 7800 },
    { label: "Oct", value: 9200 },
    { label: "Nov", value: 8900 },
    { label: "Dec", value: 10500 },
  ],
  creators: [
    { label: "Jan", value: 120 },
    { label: "Feb", value: 145 },
    { label: "Mar", value: 168 },
    { label: "Apr", value: 192 },
    { label: "May", value: 215 },
    { label: "Jun", value: 248 },
    { label: "Jul", value: 275 },
    { label: "Aug", value: 310 },
    { label: "Sep", value: 345 },
    { label: "Oct", value: 380 },
    { label: "Nov", value: 420 },
    { label: "Dec", value: 465 },
  ],
  traffic: [
    { label: "Jan", value: 12500 },
    { label: "Feb", value: 15800 },
    { label: "Mar", value: 14200 },
    { label: "Apr", value: 18900 },
    { label: "May", value: 17500 },
    { label: "Jun", value: 21000 },
    { label: "Jul", value: 19200 },
    { label: "Aug", value: 22500 },
    { label: "Sep", value: 24800 },
    { label: "Oct", value: 27200 },
    { label: "Nov", value: 29500 },
    { label: "Dec", value: 32000 },
  ],
  totals: {
    revenue: 285420.5,
    creators: 1250,
    videos: 15680,
    channels: 890,
    views: 45000000,
    visitors: 125800,
  },
};

export const mockPayoutRequests: PayoutRequest[] = [
  {
    id: "payout_001",
    creatorId: "cr_001",
    creatorName: "Tech Master",
    creatorEmail: "techmaster@example.com",
    channelName: "TechMaster Official",
    amount: 1500.0,
    currency: "USD",
    status: "pending",
    bankName: "First National Bank",
    bankAccountNumber: "1234567890",
    accountHolderName: "Tech Master",
    notes: "Monthly earnings payout",
    requestedAt: new Date("2024-01-15T10:00:00"),
  },
  {
    id: "payout_002",
    creatorId: "cr_002",
    creatorName: "Cooking Expert",
    creatorEmail: "cookingexpert@example.com",
    channelName: "Chef's Kitchen",
    amount: 850.5,
    currency: "USD",
    status: "approved",
    bankName: "Standard Bank",
    bankAccountNumber: "2345678901",
    accountHolderName: "Cooking Expert",
    notes: "",
    requestedAt: new Date("2024-01-14T14:30:00"),
    processedAt: new Date("2024-01-15T09:00:00"),
    processedBy: "Admin User",
  },
  {
    id: "payout_003",
    creatorId: "cr_005",
    creatorName: "Gaming Hub",
    creatorEmail: "gaminghub@example.com",
    channelName: "Pro Gaming Zone",
    amount: 3200.0,
    currency: "USD",
    status: "pending",
    bankName: "Capitec Bank",
    bankAccountNumber: "5678901234",
    accountHolderName: "Gaming Hub",
    notes: "Priority payout request",
    requestedAt: new Date("2024-01-15T08:00:00"),
  },
  {
    id: "payout_004",
    creatorId: "cr_003",
    creatorName: "Fitness Pro",
    creatorEmail: "fitnesspro@example.com",
    channelName: "FitLife Studio",
    amount: 450.0,
    currency: "USD",
    status: "rejected",
    bankName: "Absa Bank",
    bankAccountNumber: "3456789012",
    accountHolderName: "Fitness Pro",
    notes: "Bank details verification failed",
    requestedAt: new Date("2024-01-13T11:00:00"),
    processedAt: new Date("2024-01-14T16:00:00"),
    processedBy: "Admin User",
  },
  {
    id: "payout_005",
    creatorId: "cr_001",
    creatorName: "Tech Master",
    creatorEmail: "techmaster@example.com",
    channelName: "TechMaster Official",
    amount: 2200.0,
    currency: "USD",
    status: "completed",
    bankName: "First National Bank",
    bankAccountNumber: "1234567890",
    accountHolderName: "Tech Master",
    notes: "",
    requestedAt: new Date("2024-01-10T09:00:00"),
    processedAt: new Date("2024-01-11T10:30:00"),
    processedBy: "Admin User",
  },
  {
    id: "payout_006",
    creatorId: "cr_004",
    creatorName: "Music Channel",
    creatorEmail: "musicchannel@example.com",
    channelName: "Melody Beats",
    amount: 1800.0,
    currency: "USD",
    status: "pending",
    bankName: "Nedbank",
    bankAccountNumber: "4567890123",
    accountHolderName: "Music Channel",
    notes: "",
    requestedAt: new Date("2024-01-15T12:00:00"),
  },
];

// KYC Users Mock Data
export const mockKYCUsers: KYCUser[] = [
  {
    id: "kyc_001",
    userId: "user_001",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    selfieUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop",
    idImageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&h=250&fit=crop",
    idType: "national_id",
    idNumber: "1234567890123",
    status: "pending",
    submittedAt: new Date("2024-01-14T10:30:00"),
  },
  {
    id: "kyc_002",
    userId: "user_002",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    selfieUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop",
    idImageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&h=250&fit=crop",
    idType: "passport",
    idNumber: "A12345678",
    status: "pending_approval",
    submittedAt: new Date("2024-01-13T14:20:00"),
  },
  {
    id: "kyc_003",
    userId: "user_003",
    firstName: "Bob",
    lastName: "Wilson",
    email: "bob.wilson@example.com",
    selfieUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop",
    idImageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&h=250&fit=crop",
    idType: "drivers_license",
    idNumber: "D1234567",
    status: "approved",
    submittedAt: new Date("2024-01-10T09:15:00"),
    reviewedAt: new Date("2024-01-11T11:30:00"),
    reviewedBy: "admin@tese.com",
  },
  {
    id: "kyc_004",
    userId: "user_004",
    firstName: "Alice",
    lastName: "Brown",
    email: "alice.brown@example.com",
    selfieUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop",
    idImageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&h=250&fit=crop",
    idType: "national_id",
    idNumber: "2345678901234",
    status: "declined",
    submittedAt: new Date("2024-01-08T16:45:00"),
    reviewedAt: new Date("2024-01-09T10:00:00"),
    reviewedBy: "admin@tese.com",
    rejectionReason: "ID document is unclear",
  },
];

// Admin Users Mock Data
export const mockAdminUsers: AdminUser[] = [
  {
    id: "admin_001",
    email: "admin@tese.com",
    name: "TESE Admin",
    role: "super_admin",
    avatar: "",
    isActive: true,
    lastLogin: new Date(),
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "admin_002",
    email: "editor@tese.com",
    name: "Content Editor",
    role: "editor",
    avatar: "",
    isActive: true,
    lastLogin: new Date(Date.now() - 86400000),
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "admin_003",
    email: "auditor@tese.com",
    name: "System Auditor",
    role: "auditor",
    avatar: "",
    isActive: true,
    lastLogin: new Date(Date.now() - 172800000),
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "admin_004",
    email: "support@tese.com",
    name: "Support Staff",
    role: "admin",
    avatar: "",
    isActive: false,
    lastLogin: new Date(Date.now() - 604800000),
    createdAt: new Date("2024-02-01"),
  },
];

// Permissions Mock Data
export const mockPermissions: Permission[] = [
  { id: "perm_001", name: "users.view", description: "View users list", module: "users" },
  { id: "perm_002", name: "users.create", description: "Create new users", module: "users" },
  { id: "perm_003", name: "users.edit", description: "Edit user details", module: "users" },
  { id: "perm_004", name: "users.delete", description: "Delete users", module: "users" },
  { id: "perm_005", name: "creators.view", description: "View creators list", module: "creators" },
  { id: "perm_006", name: "creators.approve", description: "Approve/reject creators", module: "creators" },
  { id: "perm_007", name: "creators.deactivate", description: "Deactivate creators", module: "creators" },
  { id: "perm_008", name: "kyc.view", description: "View KYC applications", module: "kyc" },
  { id: "perm_009", name: "kyc.verify", description: "Verify KYC documents", module: "kyc" },
  { id: "perm_010", name: "transactions.view", description: "View transactions", module: "transactions" },
  { id: "perm_011", name: "transactions.refund", description: "Process refunds", module: "transactions" },
  { id: "perm_012", name: "transactions.export", description: "Export transactions", module: "transactions" },
  { id: "perm_013", name: "videos.view", description: "View videos", module: "videos" },
  { id: "perm_014", name: "videos.edit", description: "Edit video settings", module: "videos" },
  { id: "perm_015", name: "videos.featured", description: "Manage featured content", module: "videos" },
  { id: "perm_016", name: "settings.view", description: "View settings", module: "settings" },
  { id: "perm_017", name: "settings.edit", description: "Modify settings", module: "settings" },
  { id: "perm_018", name: "payouts.view", description: "View payouts", module: "payouts" },
  { id: "perm_019", name: "payouts.approve", description: "Approve payouts", module: "payouts" },
  { id: "perm_020", name: "payouts.complete", description: "Complete payouts", module: "payouts" },
];

// Roles Mock Data
export const mockRoles: Role[] = [
  {
    id: "role_001",
    name: "Super Admin",
    description: "Full system access",
    permissions: mockPermissions.filter((_, i) => i < 20),
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "role_002",
    name: "Admin",
    description: "Administrative access",
    permissions: mockPermissions.filter((p) =>
      ["users.view", "creators.view", "creators.approve", "kyc.view", "kyc.verify",
       "transactions.view", "transactions.refund", "videos.view", "videos.edit", "videos.featured",
       "payouts.view", "payouts.approve"].includes(p.name)
    ),
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "role_003",
    name: "Editor",
    description: "Content management access",
    permissions: mockPermissions.filter((p) =>
      ["creators.view", "videos.view", "videos.edit", "videos.featured"].includes(p.name)
    ),
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "role_004",
    name: "Auditor",
    description: "Read-only access for auditing",
    permissions: mockPermissions.filter((p) =>
      ["users.view", "creators.view", "transactions.view", "payouts.view"].includes(p.name)
    ),
    createdAt: new Date("2024-01-01"),
  },
];

// Fee Configuration Mock Data
export const mockFeeConfigurations: FeeConfiguration[] = [
  {
    id: "fee_001",
    type: "platform",
    name: "Platform Fee",
    percentage: 5.0,
    fixedAmount: 0,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "fee_002",
    type: "service",
    name: "Service Provider Fee",
    percentage: 0,
    fixedAmount: 0.50,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "fee_003",
    type: "payout",
    name: "Payout Processing Fee",
    percentage: 1.5,
    fixedAmount: 0,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "fee_004",
    type: "subscription",
    name: "Subscription Processing Fee",
    percentage: 2.5,
    fixedAmount: 0,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
];
