"use client";

import React from "react";
import {
  LayoutDashboard,
  FolderOpen,
  Users,
  Video,
  Star,
  CreditCard,
  Smartphone,
  Menu,
  X,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Search,
  Bell,
  Moon,
  Sun,
  LogOut,
  Settings,
  TrendingUp,
  TrendingDown,
  DollarSign,
  Eye,
  Radio,
  Check,
  XCircle,
  AlertCircle,
  Plus,
  Edit,
  Trash2,
  Grid,
  List,
  Shield,
  ShieldCheck,
  User,
  Home,
  MoreHorizontal,
  Filter,
  Download,
  Upload,
  RefreshCw,
  Archive,
  Lock,
  Unlock,
  Key,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Clock,
  Image,
  Music,
  File,
  Folder,
  Share2,
  Heart,
  Bookmark,
  Tag,
  Layers,
  Box,
  Briefcase,
  Target,
  Compass,
  Zap,
  Flame,
  Snowflake,
  Cloud,
  CloudRain,
  CloudLightning,
  SunMedium,
  MoonStar,
  Wifi,
  WifiOff,
  Bluetooth,
  Battery,
  BatteryCharging,
  Speaker,
  Volume2,
  VolumeX,
  Mic,
  MicOff,
  Camera,
  Monitor,
  Tablet,
  Watch,
  Printer,
  HardDrive,
  Cpu,
  Server,
  Database,
  Code,
  Terminal,
  GitBranch,
  GitCommit,
  GitPullRequest,
  GitMerge,
  GitCompare,
  Link,
  ExternalLink,
  Copy,
  Clipboard,
  ClipboardCheck,
  MousePointer,
  Fingerprint,
  QrCode,
  BarChart3,
  PieChart as PieChartIcon,
  Activity,
  Circle,
  Square,
  Triangle,
  Diamond,
  Minus,
  RotateCcw,
  RotateCw,
  Repeat,
  Shuffle,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Type,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Pen,
  PenTool,
  Brush,
  Eraser,
  Ruler,
  Calculator,
  Gift,
  Award,
  Trophy,
  BadgeCheck,
  FileText,
  FilePlus,
  FileMinus,
  FileImage,
  FileVideo,
  FileCode,
  Send,
  Inbox,
  MailOpen,
  Reply,
  Forward,
  ReplyAll,
  Flag,
  FolderHeart,
  FolderPlus,
  FolderMinus,
  Scissors,
  ClipboardPaste,
  FunctionSquare,
  CircleCheck,
  CirclePause,
  CirclePlay,
  CircleStop,
  ListOrdered,
  Play,
  PlayCircle,
  PlaySquare,
  Pause,
  PauseCircle,
  StopCircle,
  SkipBack,
  SkipForward,
  FastForward,
  Rewind,
  StepBack,
  StepForward,
  Share,
  PhoneCall,
  PhoneMissed,
  PhoneOff,
  PhoneIncoming,
  PhoneOutgoing,
  Map,
  Navigation,
  Navigation2,
  Locate,
  LocateOff,
  Crosshair,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpCircle,
  ArrowDownCircle,
  ArrowLeftCircle,
  ArrowRightCircle,
  ArrowUpLeft,
  ArrowUpRight,
  ArrowDownLeft,
  ArrowDownRight,
  ChevronsUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  Ban,
  Info,
  HelpCircle,
  AlertTriangle,
  ToggleLeft,
  ToggleRight,
  Sliders,
  Timer,
  History,
  Percent,
  Wallet,
  Laptop,
  EyeOff,
  CloudSnow,
  CloudSun,
  Hash,
  AtSign,
  XSquare,
  CircleDot,
  HashIcon,
  GripHorizontal,
  Loader2,
} from "lucide-react";

interface IconProps extends React.SVGAttributes<SVGElement> {
  className?: string;
  size?: number;
}

// Icons wrapper that maps to Lucide React icons
export const Icons = {
  // Navigation
  LayoutDashboard: (props: IconProps) => <LayoutDashboard {...props} />,
  Home: (props: IconProps) => <Home {...props} />,
  Menu: (props: IconProps) => <Menu {...props} />,
  MoreHorizontal: (props: IconProps) => <MoreHorizontal {...props} />,

  // Arrows
  ChevronDown: (props: IconProps) => <ChevronDown {...props} />,
  ChevronRight: (props: IconProps) => <ChevronRight {...props} />,
  ChevronLeft: (props: IconProps) => <ChevronLeft {...props} />,
  ArrowUp: (props: IconProps) => <ArrowUp {...props} />,
  ArrowDown: (props: IconProps) => <ArrowDown {...props} />,
  ArrowLeft: (props: IconProps) => <ArrowLeft {...props} />,
  ArrowRight: (props: IconProps) => <ArrowRight {...props} />,
  ArrowUpCircle: (props: IconProps) => <ArrowUpCircle {...props} />,
  ArrowDownCircle: (props: IconProps) => <ArrowDownCircle {...props} />,
  ArrowLeftCircle: (props: IconProps) => <ArrowLeftCircle {...props} />,
  ArrowRightCircle: (props: IconProps) => <ArrowRightCircle {...props} />,
  ArrowUpLeft: (props: IconProps) => <ArrowUpLeft {...props} />,
  ArrowUpRight: (props: IconProps) => <ArrowUpRight {...props} />,
  ArrowDownLeft: (props: IconProps) => <ArrowDownLeft {...props} />,
  ArrowDownRight: (props: IconProps) => <ArrowDownRight {...props} />,
  ChevronsUp: (props: IconProps) => <ChevronsUp {...props} />,
  ChevronsDown: (props: IconProps) => <ChevronsDown {...props} />,
  ChevronsLeft: (props: IconProps) => <ChevronsLeft {...props} />,
  ChevronsRight: (props: IconProps) => <ChevronsRight {...props} />,

  // Media Control
  Play: (props: IconProps) => <Play {...props} />,
  PlayCircle: (props: IconProps) => <PlayCircle {...props} />,
  PlaySquare: (props: IconProps) => <PlaySquare {...props} />,
  Pause: (props: IconProps) => <Pause {...props} />,
  PauseCircle: (props: IconProps) => <PauseCircle {...props} />,
  StopCircle: (props: IconProps) => <StopCircle {...props} />,
  SkipBack: (props: IconProps) => <SkipBack {...props} />,
  SkipForward: (props: IconProps) => <SkipForward {...props} />,
  FastForward: (props: IconProps) => <FastForward {...props} />,
  Rewind: (props: IconProps) => <Rewind {...props} />,
  StepBack: (props: IconProps) => <StepBack {...props} />,
  StepForward: (props: IconProps) => <StepForward {...props} />,

  // Content
  Folder: (props: IconProps) => <Folder {...props} />,
  FolderOpen: (props: IconProps) => <FolderOpen {...props} />,
  FolderPlus: (props: IconProps) => <FolderPlus {...props} />,
  FolderMinus: (props: IconProps) => <FolderMinus {...props} />,
  FolderHeart: (props: IconProps) => <FolderHeart {...props} />,
  File: (props: IconProps) => <File {...props} />,
  FileText: (props: IconProps) => <FileText {...props} />,
  FilePlus: (props: IconProps) => <FilePlus {...props} />,
  FileMinus: (props: IconProps) => <FileMinus {...props} />,
  FileImage: (props: IconProps) => <FileImage {...props} />,
  FileVideo: (props: IconProps) => <FileVideo {...props} />,
  FileCode: (props: IconProps) => <FileCode {...props} />,
  Image: (props: IconProps) => <Image {...props} />,
  Music: (props: IconProps) => <Music {...props} />,
  Video: (props: IconProps) => <Video {...props} />,

  // Communication
  Mail: (props: IconProps) => <Mail {...props} />,
  Inbox: (props: IconProps) => <Inbox {...props} />,
  MailOpen: (props: IconProps) => <MailOpen {...props} />,
  Send: (props: IconProps) => <Send {...props} />,
  Reply: (props: IconProps) => <Reply {...props} />,
  Forward: (props: IconProps) => <Forward {...props} />,
  ReplyAll: (props: IconProps) => <ReplyAll {...props} />,
  Flag: (props: IconProps) => <Flag {...props} />,
  Bell: (props: IconProps) => <Bell {...props} />,
  Phone: (props: IconProps) => <Phone {...props} />,
  PhoneCall: (props: IconProps) => <PhoneCall {...props} />,
  PhoneMissed: (props: IconProps) => <PhoneMissed {...props} />,
  PhoneOff: (props: IconProps) => <PhoneOff {...props} />,
  PhoneIncoming: (props: IconProps) => <PhoneIncoming {...props} />,
  PhoneOutgoing: (props: IconProps) => <PhoneOutgoing {...props} />,

  // User & Social
  Users: (props: IconProps) => <Users {...props} />,
  User: (props: IconProps) => <User {...props} />,
  Shield: (props: IconProps) => <Shield {...props} />,
  ShieldCheck: (props: IconProps) => <ShieldCheck {...props} />,
  Lock: (props: IconProps) => <Lock {...props} />,
  Unlock: (props: IconProps) => <Unlock {...props} />,
  DragHandle: (props: IconProps) => <GripHorizontal {...props} />,
  Loader2: (props: IconProps) => <Loader2 {...props} />,
  Key: (props: IconProps) => <Key {...props} />,
  BadgeCheck: (props: IconProps) => <BadgeCheck {...props} />,
  Heart: (props: IconProps) => <Heart {...props} />,
  Share: (props: IconProps) => <Share {...props} />,
  Share2: (props: IconProps) => <Share2 {...props} />,
  Bookmark: (props: IconProps) => <Bookmark {...props} />,
  Star: (props: IconProps) => <Star {...props} />,
  Tag: (props: IconProps) => <Tag {...props} />,

  // Actions
  Search: (props: IconProps) => <Search {...props} />,
  Filter: (props: IconProps) => <Filter {...props} />,
  Download: (props: IconProps) => <Download {...props} />,
  Upload: (props: IconProps) => <Upload {...props} />,
  Refresh: (props: IconProps) => <RefreshCw {...props} />,
  RefreshCw: (props: IconProps) => <RefreshCw {...props} />,
  RotateCcw: (props: IconProps) => <RotateCcw {...props} />,
  RotateCw: (props: IconProps) => <RotateCw {...props} />,
  Repeat: (props: IconProps) => <Repeat {...props} />,
  Repeat1: () => (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="17 1 21 5 17 9" />
      <path d="M3 11V9a4 4 0 0 1 4-4h14" />
      <polyline points="7 23 3 19 7 15" />
      <path d="M21 13v2a4 4 0 0 1-4 4H3" />
    </svg>
  ),
  Shuffle: (props: IconProps) => <Shuffle {...props} />,
  Copy: (props: IconProps) => <Copy {...props} />,
  Clipboard: (props: IconProps) => <Clipboard {...props} />,
  ClipboardCheck: (props: IconProps) => <ClipboardCheck {...props} />,
  Edit: (props: IconProps) => <Edit {...props} />,
  Trash2: (props: IconProps) => <Trash2 {...props} />,
  Trash: (props: IconProps) => <Trash2 {...props} />,
  Archive: (props: IconProps) => <Archive {...props} />,
  Link: (props: IconProps) => <Link {...props} />,
  ExternalLink: (props: IconProps) => <ExternalLink {...props} />,

  // Toggle
  Eye: (props: IconProps) => <Eye {...props} />,
  EyeOff: (props: IconProps) => <EyeOff {...props} />,

  // Status
  Check: (props: IconProps) => <Check {...props} />,
  CheckCircle: (props: IconProps) => <CircleCheck {...props} />,
  CheckSquare: () => (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="9 11 12 14 22 4" />
      <path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11" />
    </svg>
  ),
  X: (props: IconProps) => <X {...props} />,
  XCircle: (props: IconProps) => <XCircle {...props} />,
  XSquare: (props: IconProps) => <XSquare {...props} />,
  AlertCircle: (props: IconProps) => <AlertCircle {...props} />,
  AlertTriangle: (props: IconProps) => <AlertTriangle {...props} />,
  Info: (props: IconProps) => <Info {...props} />,
  HelpCircle: (props: IconProps) => <HelpCircle {...props} />,
  Ban: (props: IconProps) => <Ban {...props} />,
  Minus: (props: IconProps) => <Minus {...props} />,
  Plus: (props: IconProps) => <Plus {...props} />,

  // Theme
  Sun: (props: IconProps) => <Sun {...props} />,
  Moon: (props: IconProps) => <Moon {...props} />,
  MoonStar: (props: IconProps) => <MoonStar {...props} />,
  SunMedium: (props: IconProps) => <SunMedium {...props} />,

  // Charts & Stats
  TrendingUp: (props: IconProps) => <TrendingUp {...props} />,
  TrendingDown: (props: IconProps) => <TrendingDown {...props} />,
  BarChart: (props: IconProps) => <BarChart3 {...props} />,
  PieChart: (props: IconProps) => <PieChartIcon {...props} />,
  Activity: (props: IconProps) => <Activity {...props} />,
  DollarSign: (props: IconProps) => <DollarSign {...props} />,

  // Layout
  Grid: (props: IconProps) => <Grid {...props} />,
  List: (props: IconProps) => <List {...props} />,
  ListOrdered: (props: IconProps) => <ListOrdered {...props} />,
  AlignLeft: (props: IconProps) => <AlignLeft {...props} />,
  AlignCenter: (props: IconProps) => <AlignCenter {...props} />,
  AlignRight: (props: IconProps) => <AlignRight {...props} />,
  AlignJustify: (props: IconProps) => <AlignJustify {...props} />,

  // Devices
  Smartphone: (props: IconProps) => <Smartphone {...props} />,
  Tablet: (props: IconProps) => <Tablet {...props} />,
  Monitor: (props: IconProps) => <Monitor {...props} />,
  Laptop: (props: IconProps) => <Laptop {...props} />,
  Watch: (props: IconProps) => <Watch {...props} />,
  Camera: (props: IconProps) => <Camera {...props} />,
  Radio: (props: IconProps) => <Radio {...props} />,
  Speaker: (props: IconProps) => <Speaker {...props} />,
  Volume2: (props: IconProps) => <Volume2 {...props} />,
  VolumeX: (props: IconProps) => <VolumeX {...props} />,
  Mic: (props: IconProps) => <Mic {...props} />,
  MicOff: (props: IconProps) => <MicOff {...props} />,

  // Finance
  CreditCard: (props: IconProps) => <CreditCard {...props} />,
  Wallet: (props: IconProps) => <Wallet {...props} />,
  Percent: (props: IconProps) => <Percent {...props} />,
  Coin: () => (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8" />
      <path d="M12 6v2" />
      <path d="M12 16v2" />
    </svg>
  ),

  // Settings
  Settings: (props: IconProps) => <Settings {...props} />,
  LogOut: (props: IconProps) => <LogOut {...props} />,
  Sliders: (props: IconProps) => <Sliders {...props} />,
  ToggleLeft: (props: IconProps) => <ToggleLeft {...props} />,
  ToggleRight: (props: IconProps) => <ToggleRight {...props} />,

  // Location
  Map: (props: IconProps) => <Map {...props} />,
  MapPin: (props: IconProps) => <MapPin {...props} />,
  Navigation: (props: IconProps) => <Navigation {...props} />,
  Navigation2: (props: IconProps) => <Navigation2 {...props} />,
  Locate: (props: IconProps) => <Locate {...props} />,
  LocateOff: (props: IconProps) => <LocateOff {...props} />,
  Crosshair: (props: IconProps) => <Crosshair {...props} />,

  // Time
  Calendar: (props: IconProps) => <Calendar {...props} />,
  Clock: (props: IconProps) => <Clock {...props} />,
  Timer: (props: IconProps) => <Timer {...props} />,
  History: (props: IconProps) => <History {...props} />,

  // Weather
  Cloud: (props: IconProps) => <Cloud {...props} />,
  CloudRain: (props: IconProps) => <CloudRain {...props} />,
  CloudLightning: (props: IconProps) => <CloudLightning {...props} />,
  CloudSnow: (props: IconProps) => <CloudSnow {...props} />,
  CloudSun: (props: IconProps) => <CloudSun {...props} />,

  // Shapes
  Circle: (props: IconProps) => <Circle {...props} />,
  Square: (props: IconProps) => <Square {...props} />,
  Triangle: (props: IconProps) => <Triangle {...props} />,
  Diamond: (props: IconProps) => <Diamond {...props} />,

  // Text formatting
  Type: (props: IconProps) => <Type {...props} />,
  Bold: (props: IconProps) => <Bold {...props} />,
  Italic: (props: IconProps) => <Italic {...props} />,
  Underline: (props: IconProps) => <Underline {...props} />,
  Strikethrough: (props: IconProps) => <Strikethrough {...props} />,
  Pen: (props: IconProps) => <Pen {...props} />,
  PenTool: (props: IconProps) => <PenTool {...props} />,
  Brush: (props: IconProps) => <Brush {...props} />,
  Eraser: (props: IconProps) => <Eraser {...props} />,
  Ruler: (props: IconProps) => <Ruler {...props} />,
  Calculator: (props: IconProps) => <Calculator {...props} />,

  // Misc
  Gift: (props: IconProps) => <Gift {...props} />,
  Award: (props: IconProps) => <Award {...props} />,
  Trophy: (props: IconProps) => <Trophy {...props} />,
  Layers: (props: IconProps) => <Layers {...props} />,
  Box: (props: IconProps) => <Box {...props} />,
  Briefcase: (props: IconProps) => <Briefcase {...props} />,
  Target: (props: IconProps) => <Target {...props} />,
  Compass: (props: IconProps) => <Compass {...props} />,
  Zap: (props: IconProps) => <Zap {...props} />,
  Flame: (props: IconProps) => <Flame {...props} />,
  Snowflake: (props: IconProps) => <Snowflake {...props} />,

  // Hardware
  HardDrive: (props: IconProps) => <HardDrive {...props} />,
  Cpu: (props: IconProps) => <Cpu {...props} />,
  Server: (props: IconProps) => <Server {...props} />,
  Database: (props: IconProps) => <Database {...props} />,
  Code: (props: IconProps) => <Code {...props} />,
  Terminal: (props: IconProps) => <Terminal {...props} />,
  GitBranch: (props: IconProps) => <GitBranch {...props} />,
  GitCommit: (props: IconProps) => <GitCommit {...props} />,
  GitPullRequest: (props: IconProps) => <GitPullRequest {...props} />,
  GitMerge: (props: IconProps) => <GitMerge {...props} />,
  GitCompare: (props: IconProps) => <GitCompare {...props} />,

  // Network
  Wifi: (props: IconProps) => <Wifi {...props} />,
  WifiOff: (props: IconProps) => <WifiOff {...props} />,
  Bluetooth: (props: IconProps) => <Bluetooth {...props} />,
  Battery: (props: IconProps) => <Battery {...props} />,
  BatteryCharging: (props: IconProps) => <BatteryCharging {...props} />,
  Printer: (props: IconProps) => <Printer {...props} />,

  // Cursor
  MousePointer: (props: IconProps) => <MousePointer {...props} />,
  Cursor: (props: IconProps) => <MousePointer {...props} />,

  // Symbols
  Hash: (props: IconProps) => <HashIcon {...props} />,
  AtSign: (props: IconProps) => <AtSign {...props} />,

  // Additional
  Fingerprint: (props: IconProps) => <Fingerprint {...props} />,
  QrCode: (props: IconProps) => <QrCode {...props} />,
  Scissors: (props: IconProps) => <Scissors {...props} />,
  ClipboardPaste: (props: IconProps) => <ClipboardPaste {...props} />,
  FunctionSquare: (props: IconProps) => <FunctionSquare {...props} />,
  CircleDot: (props: IconProps) => <CircleDot {...props} />,
};
